Repository perawallet/pera-android, pull requests merged in 2024-11, with the labels that each got.

#21 PERA-1051 :: show version code and commit hash on setting screen
  app/build.gradle
  app/src/main/java/com/algorand/android/ui/settings/SettingsFragment.kt
  app/src/main/res/layout/fragment_settings.xml
Labels: gitops

#23 PERA-1079 :: Create codeowners file
  CODEOWNERS
Labels: gitops

#25 PERA-1077 :: Remove back button from the transaction confirmation screen
  app/src/main/java/com/algorand/android/ui/send/confirmation/ui/TransactionConfirmationFragment.kt
Labels: bug

#26 PERA-1090 :: Create KeyReg fragment
  app/build.gradle
  app/src/main/java/com/algorand/android/modules/accounts/di/AccountsModule.kt
  app/src/main/java/com/algorand/android/modules/accounts/domain/usecase/AccountUseCases.kt
  app/src/main/java/com/algorand/android/modules/algosdk/di/AlgoSdkModule.kt
  app/src/main/java/com/algorand/android/modules/algosdk/domain/mapper/TransactionParametersResponseMapper.kt
  app/src/main/java/com/algorand/android/modules/algosdk/domain/mapper/TransactionParametersResponseMapperImpl.kt
  app/src/main/java/com/algorand/android/modules/algosdk/domain/model/OnlineKeyRegTransactionPayload.kt
  app/src/main/java/com/algorand/android/modules/algosdk/domain/usecase/BuildKeyRegOfflineTransaction.kt
  app/src/main/java/com/algorand/android/modules/algosdk/domain/usecase/BuildKeyRegOfflineTransactionImpl.kt
  app/src/main/java/com/algorand/android/modules/algosdk/domain/usecase/BuildKeyRegOnlineTransaction.kt
  app/src/main/java/com/algorand/android/modules/algosdk/domain/usecase/BuildKeyRegOnlineTransactionImpl.kt
  app/src/main/java/com/algorand/android/modules/keyreg/di/KeyRegTransactionModule.kt
  app/src/main/java/com/algorand/android/modules/keyreg/domain/KeyRegTransactionSignManager.kt
  app/src/main/java/com/algorand/android/modules/keyreg/domain/model/KeyRegTransaction.kt
  app/src/main/java/com/algorand/android/modules/keyreg/domain/usecase/CreateKeyRegTransactionUseCase.kt
  app/src/main/java/com/algorand/android/modules/keyreg/ui/presentation/mapper/KeyRegTransactionPreviewMapper.kt
  app/src/main/java/com/algorand/android/modules/keyreg/ui/presentation/model/KeyRegTransactionDetail.kt
  app/src/main/java/com/algorand/android/modules/keyreg/ui/presentation/model/KeyRegTransactionFragmentPreview.kt
  app/src/main/java/com/algorand/android/modules/keyreg/ui/presentation/view/KeyRegSendConfirmationBottomSheet.kt
  app/src/main/java/com/algorand/android/modules/keyreg/ui/presentation/view/KeyRegTransactionFragment.kt
  app/src/main/java/com/algorand/android/modules/keyreg/ui/presentation/viewmodel/KeyRegTransactionViewModel.kt
  app/src/main/java/com/algorand/android/modules/transaction/di/TransactionModule.kt
  app/src/main/java/com/algorand/android/modules/transaction/domain/GetTransactionParams.kt
  app/src/main/res/layout/fragment_key_reg_transaction.xml
  app/src/test/java/com/algorand/android/modules/algosdk/domain/mapper/TransactionParametersResponseMapperImplTest.kt
  app/src/test/java/com/algorand/android/modules/keyreg/domain/usecase/CreateKeyRegTransactionUseCaseTest.kt
Labels: enhancement

#27 PERA-1091 :: fix bottom nav icons in API 35 devices by downgrading compileSDK
  app/src/main/java/com/algorand/android/modules/onboarding/pairledger/accountselection/ui/usecase/RegisterLedgerAccountSelectionPreviewUseCase.kt
  app/src/main/java/com/algorand/android/modules/rekey/rekeytoledgeraccount/accountselection/ui/usecase/RekeyLedgerAccountSelectionPreviewUseCase.kt
  gradle/libs.versions.toml
  versions.gradle
Labels: bug

#29 PERA-704 :: Fix summary min balance calculation
  app/arc59.properties
  app/src/main/java/com/algorand/android/modules/assetinbox/send/ui/mapper/Arc59SendSummaryPreviewMapperImpl.kt
Labels: bug

#30 PERA-1098 :: Implement remote config for cards feature
  app/build.gradle
  app/src/main/java/com/algorand/android/CoreActionsTabBarViewModel.kt
  app/src/main/java/com/algorand/android/MainActivity.kt
  app/src/main/java/com/algorand/android/core/PeraApp.kt
  app/src/main/java/com/algorand/android/customviews/CoreActionsTabBarView.kt
  app/src/main/java/com/algorand/android/koin/KoinHiltModule.kt
  app/src/main/java/com/algorand/android/koin/KoinInitializer.kt
  app/src/main/java/com/algorand/android/ui/splash/LauncherActivity.kt
  app/src/main/java/com/algorand/android/ui/splash/LauncherViewModel.kt
  gradle/libs.versions.toml
  wallet-sdk/build.gradle.kts
  wallet-sdk/src/androidMain/kotlin/com/algorand/common/remoteconfig/data/service/FirebaseRemoteConfigServiceImpl.kt
  wallet-sdk/src/commonMain/kotlin/com/algorand/common/remoteconfig/data/repository/FeatureToggleRepositoryImpl.kt
  wallet-sdk/src/commonMain/kotlin/com/algorand/common/remoteconfig/data/service/FirebaseRemoteConfigService.kt
  wallet-sdk/src/commonMain/kotlin/com/algorand/common/remoteconfig/di/RemoteConfigModule.kt
  wallet-sdk/src/commonMain/kotlin/com/algorand/common/remoteconfig/domain/repository/FeatureToggleRepository.kt
  wallet-sdk/src/commonMain/kotlin/com/algorand/common/remoteconfig/domain/usecase/InitializeOperationalToggles.kt
  wallet-sdk/src/commonMain/kotlin/com/algorand/common/remoteconfig/domain/usecase/IsFeatureToggleEnabled.kt
  wallet-sdk/src/iosMain/kotlin/com/algorand/common/remoteconfig/data/service/FirebaseRemoteConfigServiceImpl.kt
Labels: enhancement

#9 PERA-747 :: Immersve feature work (with feature flag off)
  app/build.gradle
  app/src/main/java/com/algorand/android/CoreActionsTabBarViewModel.kt
  app/src/main/java/com/algorand/android/MainActivity.kt
  app/src/main/java/com/algorand/android/core/PeraApp.kt
  app/src/main/java/com/algorand/android/customviews/CoreActionsTabBarView.kt
  app/src/main/java/com/algorand/android/deviceregistration/domain/usecase/DeviceIdUseCase.kt
  app/src/main/java/com/algorand/android/discover/home/domain/PeraMobileWebInterface.kt
  app/src/main/java/com/algorand/android/discover/utils/DiscoverJsUtils.kt
  app/src/main/java/com/algorand/android/koin/KoinHiltModule.kt
  app/src/main/java/com/algorand/android/koin/KoinInitializer.kt
  app/src/main/java/com/algorand/android/modules/card/CardsFragment.kt
  app/src/main/java/com/algorand/android/modules/card/CardsViewModel.kt
  app/src/main/java/com/algorand/android/modules/card/di/CardModule.kt
  app/src/main/java/com/algorand/android/modules/card/model/CardsPreview.kt
  app/src/main/java/com/algorand/android/modules/perawebview/GetAuthorizedAddressesWebMessage.kt
  app/src/main/java/com/algorand/android/modules/perawebview/GetAuthorizedAddressesWebMessagesUseCase.kt
  app/src/main/java/com/algorand/android/modules/perawebview/GetDeviceIdWebMessage.kt
  app/src/main/java/com/algorand/android/modules/perawebview/GetDeviceIdWebMessageUseCase.kt
  app/src/main/java/com/algorand/android/modules/perawebview/ParseOpenSystemBrowserUrl.kt
  app/src/main/java/com/algorand/android/modules/perawebview/ParseOpenSystemBrowserUrlUseCase.kt
  app/src/main/java/com/algorand/android/modules/perawebview/PeraWebMessageAction.kt
  app/src/main/java/com/algorand/android/modules/perawebview/PeraWebMessageBuilder.kt
  app/src/main/java/com/algorand/android/modules/perawebview/PeraWebMessageBuilderImpl.kt
  app/src/main/java/com/algorand/android/modules/perawebview/WebViewThemeHelper.kt
  app/src/main/java/com/algorand/android/modules/perawebview/model/PeraWebMessage.kt
  app/src/main/java/com/algorand/android/modules/walletconnect/cards/data/cache/WalletConnectCardsRequestAccountCache.kt
  app/src/main/java/com/algorand/android/modules/walletconnect/cards/data/cache/WalletConnectCardsRequestAccountCacheImpl.kt
  app/src/main/java/com/algorand/android/modules/walletconnect/cards/data/repository/WalletConnectCardsRepositoryImpl.kt
  app/src/main/java/com/algorand/android/modules/walletconnect/cards/di/WalletConnectModule.kt
  app/src/main/java/com/algorand/android/modules/walletconnect/cards/domain/helper/WalletConnectUrlSelectedAddressParser.kt
  app/src/main/java/com/algorand/android/modules/walletconnect/cards/domain/helper/WalletConnectUrlSelectedAddressParserImpl.kt
  app/src/main/java/com/algorand/android/modules/walletconnect/cards/domain/repository/WalletConnectCardsRepository.kt
  app/src/main/java/com/algorand/android/modules/walletconnect/cards/domain/usecase/CacheWalletConnectRequestPreselectedAccountAddresses.kt
  app/src/main/java/com/algorand/android/modules/walletconnect/cards/domain/usecase/CacheWalletConnectRequestPreselectedAccountAddressesUseCase.kt
  app/src/main/java/com/algorand/android/modules/walletconnect/cards/domain/usecase/ClearWalletConnectPreselectedAddressCache.kt
  app/src/main/java/com/algorand/android/modules/walletconnect/cards/domain/usecase/GetWalletConnectRequestPreselectedAccountAddresses.kt
  app/src/main/java/com/algorand/android/modules/walletconnect/domain/WalletConnectManager.kt
  app/src/main/java/com/algorand/android/ui/splash/LauncherActivity.kt
  app/src/main/java/com/algorand/android/ui/splash/LauncherViewModel.kt
  app/src/main/res/drawable/ic_cards.xml
  app/src/main/res/drawable/ic_cards_helper_button.xml
  app/src/main/res/layout/custom_core_actions_tab_bar.xml
  app/src/main/res/layout/fragment_cards.xml
  app/src/main/res/navigation/home_navigation.xml
  app/src/main/res/values/strings.xml
  app/src/test/java/com/algorand/android/modules/walletconnect/cards/domain/helper/WalletConnectUrlSelectedAddressParserImplTest.kt
  app/src/test/java/com/algorand/android/modules/walletconnect/cards/domain/usecase/CacheWalletConnectRequestPreselectedAccountAddressesUseCaseTest.kt
  gradle/libs.versions.toml
  wallet-sdk/build.gradle.kts
  wallet-sdk/src/androidMain/kotlin/com/algorand/common/remoteconfig/data/service/FirebaseRemoteConfigServiceImpl.kt
  wallet-sdk/src/commonMain/kotlin/com/algorand/common/remoteconfig/data/repository/FeatureToggleRepositoryImpl.kt
  wallet-sdk/src/commonMain/kotlin/com/algorand/common/remoteconfig/data/service/FirebaseRemoteConfigService.kt
  wallet-sdk/src/commonMain/kotlin/com/algorand/common/remoteconfig/di/RemoteConfigModule.kt
  wallet-sdk/src/commonMain/kotlin/com/algorand/common/remoteconfig/domain/repository/FeatureToggleRepository.kt
  wallet-sdk/src/commonMain/kotlin/com/algorand/common/remoteconfig/domain/usecase/InitializeOperationalToggles.kt
  wallet-sdk/src/commonMain/kotlin/com/algorand/common/remoteconfig/domain/usecase/IsFeatureToggleEnabled.kt
  wallet-sdk/src/iosMain/kotlin/com/algorand/common/remoteconfig/data/service/FirebaseRemoteConfigServiceImpl.kt
Labels: enhancement

#34 PERA-1060 :: Switch to finalized figma app staking icons
  app/src/main/res/drawable/ic_stake.xml
  app/src/main/res/drawable/ic_stake_helper_button_bg_ghost.xml
  app/src/main/res/drawable/ic_stake_helper_button_bg_gray.xml
  app/src/main/res/drawable/ic_stake_quick_actions.xml
  app/src/main/res/drawable/icn_stake.png
  app/src/main/res/layout/custom_core_actions_tab_bar.xml
  app/src/main/res/layout/item_accounts_quick_actions.xml
Labels: enhancement

#39 PERA-946 :: Change transaction status title by the flow
  app/src/main/java/com/algorand/android/modules/assetinbox/detail/receivedetail/ui/Arc59ReceiveDetailFragment.kt
  app/src/main/java/com/algorand/android/modules/assetinbox/send/ui/Arc59SendSummaryFragment.kt
  app/src/main/java/com/algorand/android/ui/send/confirmation/ui/TransactionConfirmationViewModel.kt
  app/src/main/java/com/algorand/android/ui/send/confirmation/ui/usecase/TransactionConfirmationPreviewUseCase.kt
  app/src/main/java/com/algorand/android/ui/send/transferpreview/AssetTransferPreviewFragment.kt
  app/src/main/res/layout/fragment_transaction_confirmation.xml
  app/src/main/res/navigation/arc_59_request_opt_in_navigation.xml
  app/src/main/res/navigation/asset_inbox_one_account_navigation.xml
  app/src/main/res/navigation/send_algo_navigation.xml
  app/src/main/res/navigation/transaction_confirmation_navigation.xml
  app/src/main/res/values/strings.xml
Labels: bug

#38 PERA-753 :: Show error messages for insufficient algo balance cases
  app/src/main/java/com/algorand/android/modules/assetinbox/detail/receivedetail/ui/domain/Arc59ReceiveDetailPreviewUseCase.kt
  app/src/main/java/com/algorand/android/modules/notification/domain/pagination/NotificationDataSource.kt
  app/src/main/java/com/algorand/android/utils/ErrorResource.kt
  app/src/main/res/values/strings.xml
Labels: bug

#37 PERA-1067 :: Fix the fee calculation for ARC-59 transactions
  app/src/main/java/com/algorand/android/mapper/AssetTransferPreviewMapper.kt
  app/src/main/java/com/algorand/android/ui/send/transferpreview/AssetTransferPreviewFragment.kt
  app/src/main/java/com/algorand/android/ui/send/transferpreview/AssetTransferPreviewViewModel.kt
  app/src/main/java/com/algorand/android/usecase/AssetTransferPreviewUseCase.kt
Labels: bug

#40 PERA-713 :: Handle watch account inbox notification
  app/src/main/java/com/algorand/android/MainActivity.kt
  app/src/main/res/navigation/home_navigation.xml
Labels: bug

#42 PERA-1156 :: add compose test app with bottom nav into repo
  app/build.gradle
  build.gradle.kts
  composeTestApp/build.gradle.kts
  composeTestApp/src/androidMain/AndroidManifest.xml
  composeTestApp/src/androidMain/kotlin/co/algorand/app/App.android.kt
  composeTestApp/src/androidMain/kotlin/co/algorand/app/di/AppModules.android.kt
  composeTestApp/src/androidMain/kotlin/co/algorand/app/ui/theme/Theme.android.kt
  composeTestApp/src/commonMain/composeResources/drawable/ic_collectibles.xml
  composeTestApp/src/commonMain/composeResources/drawable/ic_dark_mode.xml
  composeTestApp/src/commonMain/composeResources/drawable/ic_global.xml
  composeTestApp/src/commonMain/composeResources/drawable/ic_home.xml
  composeTestApp/src/commonMain/composeResources/drawable/ic_light_mode.xml
  composeTestApp/src/commonMain/composeResources/drawable/ic_pera.xml
  composeTestApp/src/commonMain/composeResources/drawable/ic_settings.xml
  composeTestApp/src/commonMain/composeResources/values/strings.xml
  composeTestApp/src/commonMain/kotlin/co/algorand/app/App.kt
  composeTestApp/src/commonMain/kotlin/co/algorand/app/di/AppModules.kt
  composeTestApp/src/commonMain/kotlin/co/algorand/app/di/NetworkModules.kt
  composeTestApp/src/commonMain/kotlin/co/algorand/app/di/RepositoryModules.kt
  composeTestApp/src/commonMain/kotlin/co/algorand/app/di/ViewModelModules.kt
  composeTestApp/src/commonMain/kotlin/co/algorand/app/ui/navigation/AppNavigation.kt
  composeTestApp/src/commonMain/kotlin/co/algorand/app/ui/navigation/TopBar.kt
  composeTestApp/src/commonMain/kotlin/co/algorand/app/ui/screens/DiscoverScreen.kt
  composeTestApp/src/commonMain/kotlin/co/algorand/app/ui/screens/HomeScreen.kt
  composeTestApp/src/commonMain/kotlin/co/algorand/app/ui/screens/NftsScreen.kt
  composeTestApp/src/commonMain/kotlin/co/algorand/app/ui/screens/SettingsScreen.kt
  composeTestApp/src/commonMain/kotlin/co/algorand/app/ui/theme/Color.kt
  composeTestApp/src/commonMain/kotlin/co/algorand/app/ui/theme/Theme.kt
  composeTestApp/src/commonMain/kotlin/co/algorand/app/ui/viewmodels/AlgorandBaseViewModel.kt
  composeTestApp/src/commonMain/kotlin/co/algorand/app/ui/widgets/Reusables.kt
  composeTestApp/src/commonMain/kotlin/co/algorand/app/utils/Constants.kt
  composeTestApp/src/iosMain/kotlin/co/algorand/app/App.ios.kt
  composeTestApp/src/iosMain/kotlin/co/algorand/app/di/AppModules.ios.kt
  composeTestApp/src/iosMain/kotlin/co/algorand/app/ui/theme/Theme.ios.kt
  composeTestApp/src/iosMain/kotlin/main.kt
  gradle.properties
  gradle/libs.versions.toml
  iosTestApp/iosApp.xcodeproj/project.pbxproj
  iosTestApp/iosApp.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  iosTestApp/iosApp.xcodeproj/project.xcworkspace/xcuserdata/michaeltchuang.xcuserdatad/UserInterfaceState.xcuserstate
  iosTestApp/iosApp.xcodeproj/xcuserdata/michaeltchuang.xcuserdatad/xcschemes/xcschememanagement.plist
  iosTestApp/iosApp/Assets.xcassets/AccentColor.colorset/Contents.json
  iosTestApp/iosApp/Assets.xcassets/AppIcon.appiconset/Contents.json
  iosTestApp/iosApp/Assets.xcassets/Contents.json
  iosTestApp/iosApp/Info.plist
  iosTestApp/iosApp/Preview Content/Preview Assets.xcassets/Contents.json
  iosTestApp/iosApp/iosApp.swift
  settings.gradle.kts
  versions.gradle
  wallet-sdk/build.gradle.kts
  wallet-sdk/src/commonMain/kotlin/com/algorand/common/utils/Log.kt
Labels: enhancement

#35 PERA-1025 :: Add necessary queries to cards
  app/src/main/java/com/algorand/android/discover/utils/DiscoverUtils.kt
  app/src/main/java/com/algorand/android/modules/card/CardsFragment.kt
  app/src/main/java/com/algorand/android/modules/card/CardsViewModel.kt
  app/src/main/java/com/algorand/android/modules/card/model/CardsPreview.kt
  app/src/main/java/com/algorand/android/modules/perawebview/WebViewThemeHelper.kt
  app/src/main/java/com/algorand/android/modules/staking/StakingFragment.kt
  app/src/main/java/com/algorand/android/modules/staking/StakingViewModel.kt
  app/src/main/java/com/algorand/android/modules/staking/model/StakingPreview.kt
Labels: enhancement

#45 PERA-1188 :: Add in Compose Tests
  .github/workflows/android-app-tests.yml
  composeTestApp/build.gradle.kts
Labels: gitops

#43 PERA-1165 | Move Colors, Themes, Typography into shared repo
  composeTestApp/build.gradle.kts
  composeTestApp/src/androidMain/kotlin/co/algorand/app/ui/theme/Theme.android.kt
  composeTestApp/src/commonMain/kotlin/co/algorand/app/App.kt
  composeTestApp/src/commonMain/kotlin/co/algorand/app/di/AppModules.kt
  composeTestApp/src/commonMain/kotlin/co/algorand/app/di/ViewModelModules.kt
  composeTestApp/src/commonMain/kotlin/co/algorand/app/ui/navigation/AppNavigation.kt
  composeTestApp/src/commonMain/kotlin/co/algorand/app/ui/navigation/BottomNavigationGraph.kt
  composeTestApp/src/commonMain/kotlin/co/algorand/app/ui/navigation/PeraNavigationBar.kt
  composeTestApp/src/commonMain/kotlin/co/algorand/app/ui/navigation/TopBar.kt
  composeTestApp/src/commonMain/kotlin/co/algorand/app/ui/screens/CoreActionsBottomSheet.kt
  composeTestApp/src/commonMain/kotlin/co/algorand/app/ui/screens/DiscoverScreen.kt
  composeTestApp/src/commonMain/kotlin/co/algorand/app/ui/screens/HomeScreen.kt
  composeTestApp/src/commonMain/kotlin/co/algorand/app/ui/screens/NftsScreen.kt
  composeTestApp/src/commonMain/kotlin/co/algorand/app/ui/screens/PeraTypographyPreviewScreen.kt
  composeTestApp/src/commonMain/kotlin/co/algorand/app/ui/screens/SettingsScreen.kt
  composeTestApp/src/commonMain/kotlin/co/algorand/app/ui/theme/Color.kt
  composeTestApp/src/commonMain/kotlin/co/algorand/app/ui/theme/Theme.kt
  composeTestApp/src/commonMain/kotlin/co/algorand/app/ui/viewmodels/AlgorandBaseViewModel.kt
  composeTestApp/src/commonMain/kotlin/co/algorand/app/ui/widgets/snackbar/SnackBarLayout.kt
  composeTestApp/src/commonMain/kotlin/co/algorand/app/ui/widgets/snackbar/SnackbarViewModel.kt
  composeTestApp/src/iosMain/kotlin/co/algorand/app/ui/theme/Theme.ios.kt
  gradle/libs.versions.toml
  wallet-sdk/build.gradle.kts
  wallet-sdk/src/androidMain/kotlin/com/algorand/common/ui/theme/Theme.android.kt
  wallet-sdk/src/commonMain/kotlin/com/algorand/common/ui/theme/Color.kt
  wallet-sdk/src/commonMain/kotlin/com/algorand/common/ui/theme/PeraDarkColor.kt
  wallet-sdk/src/commonMain/kotlin/com/algorand/common/ui/theme/PeraLightColor.kt
  wallet-sdk/src/commonMain/kotlin/com/algorand/common/ui/theme/Theme.kt
  wallet-sdk/src/commonMain/kotlin/com/algorand/common/ui/typography/PeraTypography.kt
  wallet-sdk/src/commonMain/kotlin/com/algorand/common/ui/typography/PeraTypographyBody.kt
  wallet-sdk/src/commonMain/kotlin/com/algorand/common/ui/typography/PeraTypographyCaption.kt
  wallet-sdk/src/commonMain/kotlin/com/algorand/common/ui/typography/PeraTypographyFootnote.kt
  wallet-sdk/src/commonMain/kotlin/com/algorand/common/ui/typography/PeraTypographyTitle.kt
  wallet-sdk/src/commonMain/kotlin/com/algorand/common/viewmodel/ViewModel.kt
  wallet-sdk/src/iosMain/kotlin/com/algorand/common/ui/theme/Theme.ios.kt
Labels: enhancement

#46 PERA-546 :: hide loader if register info fragment content loads
  app/src/main/java/com/algorand/android/modules/accounts/ui/AccountsFragment.kt
  app/src/main/java/com/algorand/android/ui/register/registerintro/RegisterIntroFragment.kt
Labels: bug

#47 PERA-931 :: Fix ARC-78 navigation issues
  app/src/main/java/com/algorand/android/modules/algosdk/domain/model/OnlineKeyRegTransactionPayload.kt
  app/src/main/java/com/algorand/android/modules/algosdk/domain/usecase/BuildKeyRegOfflineTransaction.kt
  app/src/main/java/com/algorand/android/modules/algosdk/domain/usecase/BuildKeyRegOfflineTransactionImpl.kt
  app/src/main/java/com/algorand/android/modules/algosdk/domain/usecase/BuildKeyRegOnlineTransactionImpl.kt
  app/src/main/java/com/algorand/android/modules/keyreg/domain/usecase/CreateKeyRegTransactionUseCase.kt
  app/src/main/java/com/algorand/android/modules/keyreg/ui/KeyRegTransactionFragment.kt
  app/src/main/java/com/algorand/android/modules/keyreg/ui/KeyRegTransactionViewModel.kt
  app/src/main/java/com/algorand/android/ui/send/transferamount/AssetTransferAmountFragment.kt
  app/src/main/java/com/algorand/android/ui/send/transferpreview/AssetTransferPreviewFragment.kt
  app/src/main/res/layout/bottom_sheet_swap_preview_summary.xml
  app/src/main/res/layout/fragment_key_reg_transaction.xml
  app/src/main/res/layout/fragment_transfer_asset_preview.xml
  app/src/main/res/navigation/add_note_navigation.xml
  app/src/main/res/navigation/home_navigation.xml
  app/src/main/res/navigation/send_algo_navigation.xml
Labels: bug
