Repository perawallet/pera-android, pull requests merged in 2024-10, with the labels that each got.

#11 PERA-1016 :: fix lint errors or make them more obvious with suppress
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/algorand/android/customviews/CollectibleMediaPager.kt
  app/src/main/java/com/algorand/android/customviews/ConstantCursorlessEditableTextView.kt
  app/src/main/java/com/algorand/android/ledger/LedgerBleOperationManager.kt
  app/src/main/java/com/algorand/android/modules/accounts/ui/AccountsFragment.kt
  app/src/main/java/com/algorand/android/modules/baseledgersearch/ledgersearch/ui/adapter/viewholder/LedgerSearchItemViewHolder.kt
  app/src/main/java/com/algorand/android/modules/onboarding/pairledger/search/ui/RegisterLedgerSearchFragment.kt
  app/src/main/java/com/algorand/android/modules/rekey/rekeytoledgeraccount/search/RekeyLedgerSearchFragment.kt
  app/src/main/java/com/algorand/android/ui/common/walletconnect/WalletConnectExtrasChipGroupView.kt
  app/src/main/java/com/algorand/android/utils/NavigationUtils.kt
  app/src/main/res/layout/bottom_sheet_account_detail_accounts_options.xml
  app/src/main/res/layout/custom_dialpad.xml
  app/src/main/res/layout/custom_search_bar.xml
  app/src/main/res/layout/item_nft_vertical_linear_list.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
Labels: chore

#10 PERA-735 :: Add ledger flex and stax support
  app/build.gradle
  app/src/main/java/com/algorand/android/ledger/LedgerBleConnectionManager.kt
  app/src/main/java/com/algorand/android/ledger/LedgerBleSearchManager.kt
  versions.gradle
Labels: enhancement

#3 PERA-994 :: upgrade algosdk version
  app/build.gradle
  build.gradle
  gradle/libs.versions.toml
  settings.gradle
  settings.gradle.kts
  versions.gradle
Labels: chore

#14 PERA-1023 :: Define concurrency to cancel active workflow
  .github/workflows/android-app-tests.yml
Labels: gitops

#13 PERA-1015 :: Create common module and move local account domain layer
  app/build.gradle
  gradle/libs.versions.toml
  settings.gradle.kts
  test-utils/.gitignore
  test-utils/build.gradle.kts
  test-utils/src/main/kotlin/com/algorand/test/TestObserver.kt
  wallet-sdk/build.gradle.kts
  wallet-sdk/src/androidMain/kotlin/com/algorand/common/testing/PeraFixture.kt
  wallet-sdk/src/commonMain/kotlin/com/algorand/common/account/local/model/LocalAccount.kt
  wallet-sdk/src/commonMain/kotlin/com/algorand/common/account/local/repository/Algo25AccountRepository.kt
  wallet-sdk/src/commonMain/kotlin/com/algorand/common/account/local/repository/LedgerBleAccountRepository.kt
  wallet-sdk/src/commonMain/kotlin/com/algorand/common/account/local/repository/NoAuthAccountRepository.kt
  wallet-sdk/src/commonMain/kotlin/com/algorand/common/account/local/usecase/DeleteLocalAccountUseCase.kt
  wallet-sdk/src/commonMain/kotlin/com/algorand/common/account/local/usecase/GetAllLocalAccountAddressesAsFlowUseCase.kt
  wallet-sdk/src/commonMain/kotlin/com/algorand/common/account/local/usecase/GetLocalAccountCountFlowUseCase.kt
  wallet-sdk/src/commonMain/kotlin/com/algorand/common/account/local/usecase/GetLocalAccountsUseCase.kt
  wallet-sdk/src/commonMain/kotlin/com/algorand/common/account/local/usecase/GetSecretKeyUseCase.kt
  wallet-sdk/src/commonMain/kotlin/com/algorand/common/account/local/usecase/IsThereAnyAccountWithAddressUseCase.kt
  wallet-sdk/src/commonMain/kotlin/com/algorand/common/account/local/usecase/IsThereAnyLocalAccountUseCase.kt
  wallet-sdk/src/commonMain/kotlin/com/algorand/common/account/local/usecase/LocalAccountUseCases.kt
  wallet-sdk/src/commonMain/kotlin/com/algorand/common/account/local/usecase/UpdateNoAuthAccountToAlgo25UseCase.kt
  wallet-sdk/src/commonMain/kotlin/com/algorand/common/account/local/usecase/UpdateNoAuthAccountToLedgerBleUseCase.kt
  wallet-sdk/src/commonMain/kotlin/com/algorand/common/testing/PeraFixture.kt
  wallet-sdk/src/commonTest/kotlin/com/algorand/common/account/local/usecase/DeleteLocalAccountUseCaseTest.kt
  wallet-sdk/src/commonTest/kotlin/com/algorand/common/account/local/usecase/GetAllLocalAccountAddressesAsFlowUseCaseTest.kt
  wallet-sdk/src/commonTest/kotlin/com/algorand/common/account/local/usecase/GetLocalAccountCountFlowUseCaseTest.kt
  wallet-sdk/src/commonTest/kotlin/com/algorand/common/account/local/usecase/GetLocalAccountsUseCaseTest.kt
  wallet-sdk/src/commonTest/kotlin/com/algorand/common/account/local/usecase/GetSecretKeyUseCaseTest.kt
  wallet-sdk/src/commonTest/kotlin/com/algorand/common/account/local/usecase/IsThereAnyAccountWithAddressUseCaseTest.kt
  wallet-sdk/src/commonTest/kotlin/com/algorand/common/account/local/usecase/IsThereAnyLocalAccountUseCaseTest.kt
  wallet-sdk/src/commonTest/kotlin/com/algorand/common/account/local/usecase/UpdateNoAuthAccountToAlgo25UseCaseTest.kt
  wallet-sdk/src/commonTest/kotlin/com/algorand/common/account/local/usecase/UpdateNoAuthAccountToLedgerBleUseCaseTest.kt
Labels: enhancement

#12 PERA-1020 :: move dependencies to toml file
  app/build.gradle
  app/src/main/java/com/algorand/android/usecase/AccountDetailUseCase.kt
  build.gradle
  build.gradle.kts
  gradle/libs.versions.toml
  gradle/wrapper/gradle-wrapper.properties
  versions.gradle
Labels: gitops, chore

#16 PERA-1046 :: Revert KMP Module PR causing CI error
  app/build.gradle
  build.gradle.kts
  gradle/libs.versions.toml
  settings.gradle.kts
  test-utils/.gitignore
  test-utils/build.gradle.kts
  test-utils/src/main/kotlin/com/algorand/test/TestObserver.kt
  wallet-sdk/build.gradle.kts
  wallet-sdk/src/androidMain/kotlin/com/algorand/common/testing/PeraFixture.kt
  wallet-sdk/src/commonMain/kotlin/com/algorand/common/account/local/model/LocalAccount.kt
  wallet-sdk/src/commonMain/kotlin/com/algorand/common/account/local/repository/Algo25AccountRepository.kt
  wallet-sdk/src/commonMain/kotlin/com/algorand/common/account/local/repository/LedgerBleAccountRepository.kt
  wallet-sdk/src/commonMain/kotlin/com/algorand/common/account/local/repository/NoAuthAccountRepository.kt
  wallet-sdk/src/commonMain/kotlin/com/algorand/common/account/local/usecase/DeleteLocalAccountUseCase.kt
  wallet-sdk/src/commonMain/kotlin/com/algorand/common/account/local/usecase/GetAllLocalAccountAddressesAsFlowUseCase.kt
  wallet-sdk/src/commonMain/kotlin/com/algorand/common/account/local/usecase/GetLocalAccountCountFlowUseCase.kt
  wallet-sdk/src/commonMain/kotlin/com/algorand/common/account/local/usecase/GetLocalAccountsUseCase.kt
  wallet-sdk/src/commonMain/kotlin/com/algorand/common/account/local/usecase/GetSecretKeyUseCase.kt
  wallet-sdk/src/commonMain/kotlin/com/algorand/common/account/local/usecase/IsThereAnyAccountWithAddressUseCase.kt
  wallet-sdk/src/commonMain/kotlin/com/algorand/common/account/local/usecase/IsThereAnyLocalAccountUseCase.kt
  wallet-sdk/src/commonMain/kotlin/com/algorand/common/account/local/usecase/LocalAccountUseCases.kt
  wallet-sdk/src/commonMain/kotlin/com/algorand/common/account/local/usecase/UpdateNoAuthAccountToAlgo25UseCase.kt
  wallet-sdk/src/commonMain/kotlin/com/algorand/common/account/local/usecase/UpdateNoAuthAccountToLedgerBleUseCase.kt
  wallet-sdk/src/commonMain/kotlin/com/algorand/common/testing/PeraFixture.kt
  wallet-sdk/src/commonTest/kotlin/com/algorand/common/account/local/usecase/DeleteLocalAccountUseCaseTest.kt
  wallet-sdk/src/commonTest/kotlin/com/algorand/common/account/local/usecase/GetAllLocalAccountAddressesAsFlowUseCaseTest.kt
  wallet-sdk/src/commonTest/kotlin/com/algorand/common/account/local/usecase/GetLocalAccountCountFlowUseCaseTest.kt
  wallet-sdk/src/commonTest/kotlin/com/algorand/common/account/local/usecase/GetLocalAccountsUseCaseTest.kt
  wallet-sdk/src/commonTest/kotlin/com/algorand/common/account/local/usecase/GetSecretKeyUseCaseTest.kt
  wallet-sdk/src/commonTest/kotlin/com/algorand/common/account/local/usecase/IsThereAnyAccountWithAddressUseCaseTest.kt
  wallet-sdk/src/commonTest/kotlin/com/algorand/common/account/local/usecase/IsThereAnyLocalAccountUseCaseTest.kt
  wallet-sdk/src/commonTest/kotlin/com/algorand/common/account/local/usecase/UpdateNoAuthAccountToAlgo25UseCaseTest.kt
  wallet-sdk/src/commonTest/kotlin/com/algorand/common/account/local/usecase/UpdateNoAuthAccountToLedgerBleUseCaseTest.kt
Labels: gitops

#17 PERA-1047 :: Add in app bundle publish test
  .github/pull_request_template.md
  .github/workflows/android-app-tests.yml
  versions.gradle
Labels: gitops

#19 PERA-713 :: Remove watch accounts from the inbox
  app/src/main/java/com/algorand/android/core/AccountManager.kt
  app/src/main/java/com/algorand/android/modules/assetinbox/assetinboxallaccounts/domain/usecase/AssetInboxAllAccountsUseCase.kt
  app/src/main/java/com/algorand/android/modules/assetinbox/assetinboxallaccounts/ui/usecase/AssetInboxAllAccountsPreviewUseCase.kt
  versions.gradle
Labels: bug

#20 PERA-929 :: Amount of ASA in asset inbox not displayed correctly
  app/src/main/java/com/algorand/android/modules/assetinbox/assetinboxoneaccount/data/mapper/AssetInboxOneAccountMapperImpl.kt
  app/src/main/java/com/algorand/android/modules/assetinbox/assetinboxoneaccount/data/model/AssetInboxOneAccountPaginatedResponse.kt
  app/src/main/java/com/algorand/android/modules/assetinbox/assetinboxoneaccount/di/AssetInboxOneAccountRepositoryModule.kt
  app/src/main/java/com/algorand/android/modules/assetinbox/assetinboxoneaccount/domain/model/AssetInboxOneAccountPaginated.kt
  app/src/main/java/com/algorand/android/modules/assetinbox/assetinboxoneaccount/ui/mapper/AssetInboxOneAccountPreviewMapperImpl.kt
Labels: bug
