Repository perawallet/pera-android, pull requests merged in 2024-12, with the labels that each got.

#49 PERA-1217 :: bump up version number to 5.14.0
  gradle/libs.versions.toml
Labels: gitops

#51 PERA-1183 :: Create QR Scanner in common module
  app/src/main/java/com/algorand/android/modules/qrscanning/BaseQrScannerFragment.kt
  app/src/main/java/com/algorand/android/modules/qrscanning/QrScannerView.kt
  app/src/main/res/layout/fragment_qr_code_scanner.xml
  composeTestApp/src/commonMain/kotlin/co/algorand/app/ui/navigation/AppNavigation.kt
  composeTestApp/src/commonMain/kotlin/co/algorand/app/ui/screens/HomeScreen.kt
  composeTestApp/src/commonMain/kotlin/co/algorand/app/ui/screens/QrScannerScreen.kt
  gradle/libs.versions.toml
  wallet-sdk/build.gradle.kts
  wallet-sdk/src/androidMain/kotlin/com/algorand/common/qr/presentation/view/BarcodeScanner.android.kt
  wallet-sdk/src/commonMain/kotlin/com/algorand/common/qr/presentation/view/BarcodeScanner.kt
  wallet-sdk/src/commonMain/kotlin/com/algorand/common/qr/presentation/view/CameraOverlay.kt
  wallet-sdk/src/commonMain/kotlin/com/algorand/common/qr/presentation/view/QrScanner.kt
  wallet-sdk/src/iosMain/kotlin/com/algorand/common/qr/presentation/view/BarcodeScanner.ios.kt
Labels: enhancement

#52 PERA-1237 :: fix staking JS callbacks in staking screen
  app/src/main/java/com/algorand/android/discover/home/domain/PeraMobileWebInterface.kt
  app/src/main/java/com/algorand/android/modules/card/CardsFragment.kt
  app/src/main/java/com/algorand/android/modules/staking/StakingFragment.kt
  app/src/main/java/com/algorand/android/modules/staking/StakingViewModel.kt
  app/src/main/res/navigation/home_navigation.xml
Labels: bug

#53 PERA-1228 :: Create local account db and necessary use cases
  composeTestApp/src/commonMain/kotlin/co/algorand/app/di/AppModules.kt
  composeTestApp/src/commonMain/kotlin/co/algorand/app/di/ViewModelModules.kt
  composeTestApp/src/commonMain/kotlin/co/algorand/app/ui/navigation/AppNavigation.kt
  composeTestApp/src/commonMain/kotlin/co/algorand/app/ui/navigation/BottomNavigationGraph.kt
  composeTestApp/src/commonMain/kotlin/co/algorand/app/ui/navigation/PeraNavigationBar.kt
  composeTestApp/src/commonMain/kotlin/co/algorand/app/ui/screens/HomeScreen.kt
  composeTestApp/src/commonMain/kotlin/co/algorand/app/ui/screens/SettingsScreen.kt
  composeTestApp/src/commonMain/kotlin/co/algorand/app/ui/screens/home/AccountsScreen.kt
  composeTestApp/src/commonMain/kotlin/co/algorand/app/ui/screens/home/AccountsViewModel.kt
  wallet-sdk/build.gradle.kts
  wallet-sdk/src/androidMain/kotlin/com/algorand/common/account/local/data/database/AccountDatabase.android.kt
  wallet-sdk/src/androidMain/kotlin/com/algorand/common/algosdk/AlgoAccountSdk.android.kt
  wallet-sdk/src/androidMain/kotlin/com/algorand/common/di/PlatformKoinModule.android.kt
  wallet-sdk/src/androidUnitTest/kotlin/com/algorand/common/account/local/data/mapper/entity/Algo25EntityMapperImplTest.kt
  wallet-sdk/src/androidUnitTest/kotlin/com/algorand/common/account/local/data/mapper/entity/LedgerBleEntityMapperImplTest.kt
  wallet-sdk/src/androidUnitTest/kotlin/com/algorand/common/account/local/data/mapper/entity/NoAuthEntityMapperImplTest.kt
  wallet-sdk/src/androidUnitTest/kotlin/com/algorand/common/account/local/data/mapper/model/Algo25MapperImplTest.kt
  wallet-sdk/src/androidUnitTest/kotlin/com/algorand/common/account/local/data/mapper/model/LedgerBleMapperImplTest.kt
  wallet-sdk/src/androidUnitTest/kotlin/com/algorand/common/account/local/data/mapper/model/NoAuthMapperImplTest.kt
  wallet-sdk/src/androidUnitTest/kotlin/com/algorand/common/account/local/data/repository/Algo25AccountRepositoryImplTest.kt
  wallet-sdk/src/androidUnitTest/kotlin/com/algorand/common/account/local/data/repository/LedgerBleAccountRepositoryImplTest.kt
  wallet-sdk/src/androidUnitTest/kotlin/com/algorand/common/account/local/data/repository/NoAuthAccountRepositoryImplTest.kt
  wallet-sdk/src/androidUnitTest/kotlin/com/algorand/common/account/local/domain/usecase/DeleteLocalAccountUseCaseTest.kt
  wallet-sdk/src/androidUnitTest/kotlin/com/algorand/common/account/local/domain/usecase/GetAllLocalAccountAddressesAsFlowUseCaseTest.kt
  wallet-sdk/src/androidUnitTest/kotlin/com/algorand/common/account/local/domain/usecase/GetLocalAccountCountFlowUseCaseTest.kt
  wallet-sdk/src/androidUnitTest/kotlin/com/algorand/common/account/local/domain/usecase/GetLocalAccountsUseCaseTest.kt
  wallet-sdk/src/androidUnitTest/kotlin/com/algorand/common/account/local/domain/usecase/GetSecretKeyUseCaseTest.kt
  wallet-sdk/src/androidUnitTest/kotlin/com/algorand/common/account/local/domain/usecase/IsThereAnyAccountWithAddressUseCaseTest.kt
  wallet-sdk/src/androidUnitTest/kotlin/com/algorand/common/account/local/domain/usecase/IsThereAnyLocalAccountUseCaseTest.kt
  wallet-sdk/src/androidUnitTest/kotlin/com/algorand/common/account/local/domain/usecase/UpdateNoAuthAccountToAlgo25UseCaseTest.kt
  wallet-sdk/src/androidUnitTest/kotlin/com/algorand/common/account/local/domain/usecase/UpdateNoAuthAccountToLedgerBleUseCaseTest.kt
  wallet-sdk/src/commonMain/kotlin/com/algorand/common/account/local/data/database/AccountDatabase.kt
  wallet-sdk/src/commonMain/kotlin/com/algorand/common/account/local/di/LocalAccountsKoinModule.kt
  wallet-sdk/src/commonMain/kotlin/com/algorand/common/algosdk/AlgoAccountSdk.kt
  wallet-sdk/src/commonMain/kotlin/com/algorand/common/algosdk/model/Algo25Account.kt
  wallet-sdk/src/commonMain/kotlin/com/algorand/common/di/PlatformKoinModule.kt
  wallet-sdk/src/commonMain/kotlin/com/algorand/common/encryption/AddressEncryptionManagerImpl.kt
  wallet-sdk/src/commonMain/kotlin/com/algorand/common/encryption/SecretKeyEncryptionManagerImpl.kt
  wallet-sdk/src/commonMain/kotlin/com/algorand/common/encryption/di/EncryptionKoinModule.kt
  wallet-sdk/src/iosMain/kotlin/com/algorand/common/account/local/data/database/AccountDatabase.ios.kt
  wallet-sdk/src/iosMain/kotlin/com/algorand/common/algosdk/AlgoAccountSdk.ios.kt
  wallet-sdk/src/iosMain/kotlin/com/algorand/common/di/PlatformKoinModule.ios.kt
Labels: enhancement

#56 PERA-1245 :: hide favorites button in bottom nav of staking webview
  app/src/main/java/com/algorand/android/discover/dapp/ui/DiscoverDappFragment.kt
  app/src/main/java/com/algorand/android/discover/dapp/ui/DiscoverDappViewModel.kt
  app/src/main/java/com/algorand/android/discover/dapp/ui/model/DiscoverDappPreview.kt
  app/src/main/java/com/algorand/android/discover/dapp/ui/usecase/DiscoverDappPreviewUseCase.kt
  app/src/main/java/com/algorand/android/discover/home/ui/DiscoverHomeFragment.kt
  app/src/main/java/com/algorand/android/modules/staking/StakingFragment.kt
  app/src/main/res/navigation/discover_dapp_navigation.xml
  app/src/main/res/navigation/discover_home_navigation.xml
  app/src/main/res/navigation/discover_url_viewer_navigation.xml
  app/src/main/res/navigation/home_navigation.xml
Labels: bug

#55 PERA-977 :: Add ASA ID next to shortName in description
  app/src/main/java/com/algorand/android/modules/accountdetail/assets/ui/adapter/OwnedAssetViewHolder.kt
  app/src/main/java/com/algorand/android/modules/accountdetail/assets/ui/model/AccountDetailAssetsItem.kt
Labels: enhancement

#54 PERA-1060 :: Add new icon next to stake bottom nav icon per figma design
  app/src/main/java/com/algorand/android/customviews/ListNewMenuItemView.kt
  app/src/main/java/com/algorand/android/modules/accountdetail/assets/ui/adapter/OwnedAssetViewHolder.kt
  app/src/main/res/drawable/ic_new_badge.xml
  app/src/main/res/layout/custom_core_actions_tab_bar.xml
  app/src/main/res/layout/custom_list_new_menu_item_view.xml
  app/src/main/res/values/strings.xml
Labels: enhancement

#58 PERA-977 :: Switch to middle dot
  app/src/main/java/com/algorand/android/modules/accountdetail/assets/ui/adapter/OwnedAssetViewHolder.kt
Labels: bug

#63 PERA-1236 :: Show asset short name near the amount
  app/src/main/java/com/algorand/android/modules/assetinbox/detail/transactiondetail/mapper/Arc59TransactionDetailPreviewMapperImpl.kt
Labels: bug

#61 PERA-1269 :: Change text on ARC-59 info screen
  app/src/main/res/values/strings.xml
Labels: enhancement

#62 PERA-1235 :: Show usd value of the asset transfer request
  app/src/main/java/com/algorand/android/modules/assetinbox/detail/transactiondetail/mapper/Arc59TransactionDetailPreviewMapperImpl.kt
Labels: bug

#60 PERA-1194 :: Create ARC-59 express send warning screen
  app/src/main/java/com/algorand/android/modules/assetinbox/expresssend/domain/usecase/Arc59ExpressSend.kt
  app/src/main/java/com/algorand/android/modules/assetinbox/expresssend/domain/usecase/Arc59ExpressSendUseCase.kt
  app/src/main/java/com/algorand/android/modules/assetinbox/expresssend/ui/Arc59ExpressSendFragment.kt
  app/src/main/java/com/algorand/android/modules/assetinbox/expresssend/ui/Arc59ExpressSendViewModel.kt
  app/src/main/java/com/algorand/android/ui/send/assetselection/AssetSelectionViewModel.kt
  app/src/main/java/com/algorand/android/ui/send/receiveraccount/ReceiverAccountSelectionFragment.kt
  app/src/main/java/com/algorand/android/ui/send/receiveraccount/ReceiverAccountSelectionViewModel.kt
  app/src/main/java/com/algorand/android/ui/send/senderaccount/SenderAccountSelectionFragment.kt
  app/src/main/java/com/algorand/android/ui/send/senderaccount/SenderAccountSelectionViewModel.kt
  app/src/main/java/com/algorand/android/ui/send/transferamount/AssetTransferAmountFragment.kt
  app/src/main/java/com/algorand/android/ui/send/transferamount/AssetTransferAmountViewModel.kt
  app/src/main/java/com/algorand/android/usecase/AssetSelectionUseCase.kt
  app/src/main/java/com/algorand/android/usecase/AssetTransferAmountUseCase.kt
  app/src/main/java/com/algorand/android/usecase/SenderAccountSelectionPreviewUseCase.kt
  app/src/main/java/com/algorand/android/usecase/SenderAccountSelectionUseCase.kt
  app/src/main/java/com/algorand/android/utils/preference/SharedPrefUtils.kt
  app/src/main/res/drawable/ic_express_send.xml
  app/src/main/res/layout/fragment_arc59_express_send.xml
  app/src/main/res/navigation/asset_inbox_info_navigation.xml
  app/src/main/res/navigation/send_algo_navigation.xml
  app/src/main/res/values/donottranslate.xml
  app/src/main/res/values/strings.xml
Labels: enhancement

#65 PERA-1267 :: Missing default minimum fee in ARC-78 implementation
  app/src/main/java/com/algorand/android/modules/keyreg/ui/components/KeyRegTable.kt
  app/src/main/java/com/algorand/android/modules/keyreg/ui/mapper/KeyRegTransactionPreviewMapper.kt
  app/src/main/java/com/algorand/android/modules/keyreg/ui/model/KeyRegTransactionPreview.kt
Labels: bug

#75 PERA-1194 :: Fix express send page copy issues
  app/src/main/res/layout/fragment_arc59_express_send.xml
Labels: bug

#79 PERA-1328 :: Fix account import QR code parsing
  wallet-sdk/src/commonMain/kotlin/com/algorand/common/deeplink/parser/query/MnemonicQueryParser.kt
  wallet-sdk/src/commonMain/kotlin/com/algorand/common/deeplink/utils/CoinbaseDeepLinkUtils.kt
Labels: bug

#78 PERA-1301 :: Add CLA github action job
  .github/workflows/cla.yml
  CONTRIBUTING.md
Labels: gitops

#82 PERA-1301 :: Add in PAT token
  .github/workflows/cla.yml
Labels: bug, gitops

#72 PERA-1335 :: fix koin view model not working for ios test app
  gradle/libs.versions.toml
  wallet-sdk/build.gradle.kts
  wallet-sdk/src/androidMain/kotlin/com/algorand/common/account/local/data/database/AccountDatabase.android.kt
  wallet-sdk/src/iosMain/kotlin/com/algorand/common/account/local/data/database/AccountDatabase.ios.kt
Labels: bug, external contribution

#81 PERA-725 :: Fetch asset detail from node when indexer fails
  app/src/main/java/com/algorand/android/utils/walletconnect/WalletConnectCustomTransactionAssetDetailHandler.kt
Labels: enhancement

#84 PERA-1337 :: Bump up dev branch to 5.15.0
  gradle/libs.versions.toml
Labels: gitops, chore

#83 PERA-1336 :: Merge CLA Signatures Batch 1
  cla-signatures/v1/cla.json
Labels: enhancement

#86 PERA-1345 :: Add pera usernames to CLA filter
  .github/workflows/cla.yml
  gradle/libs.versions.toml
Labels: gitops

#59 PERA-1263 :: Add Bip39 libraries and create/recover Algo25 using AlgoSDK in common module
  app/build.gradle
  composeTestApp/src/androidMain/AndroidManifest.xml
  composeTestApp/src/androidMain/res/xml/data_extraction_rules.xml
  gradle/libs.versions.toml
  wallet-sdk/build.gradle.kts
  wallet-sdk/src/androidMain/kotlin/com/algorand/common/algosdk/AlgoAccountSdk.android.kt
  wallet-sdk/src/commonMain/kotlin/com/algorand/common/algosdk/AlgoAccountSdk.kt
  wallet-sdk/src/iosMain/kotlin/com/algorand/common/algosdk/AlgoAccountSdk.ios.kt
Labels: enhancement

#90 PERA-1364 :: fix testnet/mainnet webview base urls for staging builds
  app/build.gradle
  app/src/main/java/com/algorand/android/CoreActionsTabBarViewModel.kt
  app/src/main/java/com/algorand/android/CoreMainActivity.kt
  app/src/main/java/com/algorand/android/MainActivity.kt
  app/src/main/java/com/algorand/android/core/BaseFragment.kt
  app/src/main/java/com/algorand/android/customviews/CoreActionsTabBarView.kt
  app/src/main/java/com/algorand/android/discover/detail/ui/DiscoverDetailFragment.kt
  app/src/main/java/com/algorand/android/discover/detail/ui/DiscoverDetailViewModel.kt
  app/src/main/java/com/algorand/android/discover/home/ui/DiscoverHomeFragment.kt
  app/src/main/java/com/algorand/android/discover/home/ui/DiscoverHomeViewModel.kt
  app/src/main/java/com/algorand/android/discover/utils/DiscoverUrlBuilder.kt
  app/src/main/java/com/algorand/android/discover/utils/DiscoverUtils.kt
  app/src/main/java/com/algorand/android/modules/card/CardsFragment.kt
  app/src/main/java/com/algorand/android/modules/card/CardsViewModel.kt
  app/src/main/java/com/algorand/android/modules/dapp/meld/ui/intro/MeldIntroViewModel.kt
  app/src/main/java/com/algorand/android/modules/staking/StakingFragment.kt
  app/src/main/java/com/algorand/android/modules/staking/StakingViewModel.kt
  app/src/main/java/com/algorand/android/utils/BaseUrlBuilder.kt
Labels: bug

#94 PERA-1374 :: Migrate account creation flow
  app/src/main/java/com/algorand/android/koin/KoinHiltModule.kt
  app/src/main/java/com/algorand/android/koin/KoinInitializer.kt
  app/src/main/java/com/algorand/android/models/AccountCreation.kt
  app/src/main/java/com/algorand/android/modules/accounts/di/AccountsKoinModule.kt
  app/src/main/java/com/algorand/android/modules/asb/importbackup/accountselection/ui/usecase/AsbImportAccountSelectionPreviewUseCase.kt
  app/src/main/java/com/algorand/android/modules/onboarding/pairledger/verifyselectedaccount/ui/VerifyLedgerAddressViewModel.kt
  app/src/main/java/com/algorand/android/modules/onboarding/recoverypassphrase/enterpassphrase/ui/usecase/RecoverWithPassphrasePreviewUseCase.kt
  app/src/main/java/com/algorand/android/modules/onboarding/recoverypassphrase/rekeyedaccountselection/selection/ui/RekeyedAccountSelectionViewModel.kt
  app/src/main/java/com/algorand/android/modules/onboarding/recoverypassphrase/rekeyedaccountselection/selection/ui/usecase/RekeyedAccountSelectionPreviewUseCase.kt
  app/src/main/java/com/algorand/android/modules/onboarding/registerwatchaccount/ui/usecase/WatchAccountRegistrationPreviewUseCase.kt
  app/src/main/java/com/algorand/android/modules/rekey/rekeytoledgeraccount/confirmation/ui/usecase/RekeyToLedgerAccountConfirmationPreviewUseCase.kt
  app/src/main/java/com/algorand/android/modules/rekey/rekeytostandardaccount/confirmation/ui/usecase/RekeyToStandardAccountConfirmationPreviewUseCase.kt
  app/src/main/java/com/algorand/android/modules/rekey/undorekey/confirmation/ui/usecase/UndoRekeyConfirmationPreviewUseCase.kt
  app/src/main/java/com/algorand/android/modules/webimport/loading/domain/usecase/WebImportAccountDecryptionUseCase.kt
  app/src/main/java/com/algorand/android/ui/common/warningconfirmation/BackupInfoFragment.kt
  app/src/main/java/com/algorand/android/ui/register/BackupPassphraseFragment.kt
  app/src/main/java/com/algorand/android/ui/register/PassphraseValidationFragment.kt
  app/src/main/java/com/algorand/android/ui/register/createaccount/passphraseverified/PassphraseVerifiedInfoFragment.kt
  app/src/main/java/com/algorand/android/ui/register/nameregistration/BaseNameRegistrationFragment.kt
  app/src/main/java/com/algorand/android/ui/register/nameregistration/NameRegistrationViewModel.kt
  app/src/main/java/com/algorand/android/usecase/AccountAdditionUseCase.kt
  app/src/main/java/com/algorand/android/usecase/NameRegistrationPreviewUseCase.kt
  composeTestApp/src/commonMain/kotlin/co/algorand/app/ui/screens/accounts/AccountsViewModel.kt
  wallet-sdk/src/androidUnitTest/kotlin/com/algorand/common/account/local/domain/usecase/UpdateNoAuthAccountToAlgo25UseCaseTest.kt
  wallet-sdk/src/androidUnitTest/kotlin/com/algorand/common/account/local/domain/usecase/UpdateNoAuthAccountToBip39UseCaseTest.kt
  wallet-sdk/src/androidUnitTest/kotlin/com/algorand/common/account/local/domain/usecase/UpdateNoAuthAccountToLedgerBleUseCaseTest.kt
  wallet-sdk/src/commonMain/kotlin/com/algorand/common/account/core/di/AccountCoreKoinModule.kt
  wallet-sdk/src/commonMain/kotlin/com/algorand/common/account/core/domain/model/CreateAccount.kt
  wallet-sdk/src/commonMain/kotlin/com/algorand/common/account/core/domain/usecase/AccountCoreUseCases.kt
  wallet-sdk/src/commonMain/kotlin/com/algorand/common/account/core/domain/usecase/AddAlgo25AccountUseCase.kt
  wallet-sdk/src/commonMain/kotlin/com/algorand/common/account/core/domain/usecase/AddBip39AccountUseCase.kt
  wallet-sdk/src/commonMain/kotlin/com/algorand/common/account/core/domain/usecase/AddLedgerBleAccountUseCase.kt
  wallet-sdk/src/commonMain/kotlin/com/algorand/common/account/core/domain/usecase/AddNoAuthAccountUseCase.kt
  wallet-sdk/src/commonMain/kotlin/com/algorand/common/account/custom/data/database/dao/CustomInfoDao.kt
  wallet-sdk/src/commonMain/kotlin/com/algorand/common/account/custom/data/database/model/CustomInfoEntity.kt
  wallet-sdk/src/commonMain/kotlin/com/algorand/common/account/custom/data/mapper/entity/CustomInfoEntityMapper.kt
  wallet-sdk/src/commonMain/kotlin/com/algorand/common/account/custom/data/mapper/entity/CustomInfoEntityMapperImpl.kt
  wallet-sdk/src/commonMain/kotlin/com/algorand/common/account/custom/data/mapper/model/CustomInfoMapper.kt
  wallet-sdk/src/commonMain/kotlin/com/algorand/common/account/custom/data/mapper/model/CustomInfoMapperImpl.kt
  wallet-sdk/src/commonMain/kotlin/com/algorand/common/account/custom/data/repository/CustomInfoRepositoryImpl.kt
  wallet-sdk/src/commonMain/kotlin/com/algorand/common/account/custom/di/CustomInfoKoinModule.kt
  wallet-sdk/src/commonMain/kotlin/com/algorand/common/account/custom/domain/model/CustomInfo.kt
  wallet-sdk/src/commonMain/kotlin/com/algorand/common/account/custom/domain/repository/CustomInfoRepository.kt
  wallet-sdk/src/commonMain/kotlin/com/algorand/common/account/custom/domain/usecase/CustomInfoUseCases.kt
  wallet-sdk/src/commonMain/kotlin/com/algorand/common/account/info/di/AccountInformationKoinModule.kt
  wallet-sdk/src/commonMain/kotlin/com/algorand/common/account/info/domain/usecase/AccountInformationUseCases.kt
  wallet-sdk/src/commonMain/kotlin/com/algorand/common/account/info/domain/usecase/IsThereAnyCachedErrorAccountUseCase.kt
  wallet-sdk/src/commonMain/kotlin/com/algorand/common/account/info/domain/usecase/IsThereAnyCachedSuccessAccountUseCase.kt
  wallet-sdk/src/commonMain/kotlin/com/algorand/common/account/local/di/LocalAccountsKoinModule.kt
  wallet-sdk/src/commonMain/kotlin/com/algorand/common/account/local/domain/model/LocalAccount.kt
  wallet-sdk/src/commonMain/kotlin/com/algorand/common/account/local/domain/usecase/IsThereAnyNoAuthAccountWithAddressUseCase.kt
  wallet-sdk/src/commonMain/kotlin/com/algorand/common/account/local/domain/usecase/LocalAccountUseCases.kt
  wallet-sdk/src/commonMain/kotlin/com/algorand/common/account/local/domain/usecase/UpdateNoAuthAccountToAlgo25UseCase.kt
  wallet-sdk/src/commonMain/kotlin/com/algorand/common/account/local/domain/usecase/UpdateNoAuthAccountToBip39UseCase.kt
  wallet-sdk/src/commonMain/kotlin/com/algorand/common/account/local/domain/usecase/UpdateNoAuthAccountToLedgerBleUseCase.kt
  wallet-sdk/src/commonMain/kotlin/com/algorand/common/di/CommonModuleKoinModules.kt
  wallet-sdk/src/commonMain/kotlin/com/algorand/common/foundation/database/PeraDatabase.kt
Labels: enhancement
