Repository perawallet/pera-android, pull requests merged in 2025-05, with the labels that each got.

#273 PERA-1984 :: Ledger connection screen copy change
  app/src/main/res/values/strings.xml
Labels: chore

#280 PERA-2124 :: Update caching algorithm to prevent unnecessary updates
  app/src/main/kotlin/com/algorand/android/decider/AssetDrawableProviderDecider.kt
  app/src/main/kotlin/com/algorand/android/modules/accounts/lite/domain/manager/AccountLiteManagerImpl.kt
  app/src/main/kotlin/com/algorand/android/ui/send/transferamount/BalanceWarningBottomSheet.kt
  app/src/main/kotlin/com/algorand/android/utils/assetdrawable/AlgoDrawableProvider.kt
  common-sdk/schemas/com.algorand.wallet.foundation.database.PeraDatabase/4.json
  common-sdk/src/main/kotlin/com/algorand/wallet/account/info/data/database/dao/AccountInformationDao.kt
  common-sdk/src/main/kotlin/com/algorand/wallet/account/info/data/database/dao/AssetHoldingDao.kt
  common-sdk/src/main/kotlin/com/algorand/wallet/account/info/data/database/model/AssetHoldingDto.kt
  common-sdk/src/main/kotlin/com/algorand/wallet/account/info/data/database/model/AssetHoldingEntity.kt
  common-sdk/src/main/kotlin/com/algorand/wallet/account/info/data/repository/AccountInformationRepositoryImpl.kt
  common-sdk/src/main/kotlin/com/algorand/wallet/account/info/data/repository/AssetHoldingCacheHelperImpl.kt
  common-sdk/src/main/kotlin/com/algorand/wallet/asset/data/database/dao/AssetDetailDao.kt
  common-sdk/src/main/kotlin/com/algorand/wallet/asset/data/database/dao/CollectibleDao.kt
  common-sdk/src/main/kotlin/com/algorand/wallet/asset/data/database/dao/PaginatedAssetCollectibleDao.kt
  common-sdk/src/main/kotlin/com/algorand/wallet/asset/data/database/model/CollectibleEntity.kt
  common-sdk/src/main/kotlin/com/algorand/wallet/asset/data/repository/AssetRepositoryImpl.kt
  common-sdk/src/main/kotlin/com/algorand/wallet/foundation/database/PeraDatabase.kt
  common-sdk/src/main/kotlin/com/algorand/wallet/foundation/database/PeraDatabaseModule.kt
  common-sdk/src/main/kotlin/com/algorand/wallet/foundation/database/migration/PeraDatabaseMigration3to4.kt
  common-sdk/src/main/kotlin/com/algorand/wallet/foundation/database/util/DaoUtils.kt
  common-sdk/src/test/kotlin/com/algorand/wallet/account/info/data/repository/AssetHoldingCacheHelperImplTest.kt
  common-sdk/src/test/kotlin/com/algorand/wallet/asset/data/mapper/model/collectible/CollectibleMapperImplTest.kt
Labels: bug

#279 PERA-1773 :: Show confetti animation on account creation event
  app/src/main/kotlin/com/algorand/android/modules/accounts/ui/view/AccountsFragment.kt
  app/src/main/kotlin/com/algorand/android/modules/accounts/ui/viewmodel/AccountsViewModel.kt
  app/src/main/kotlin/com/algorand/android/ui/register/createaccount/name/CreateAccountNameRegistrationFragment.kt
  app/src/main/res/layout/fragment_accounts.xml
  app/src/main/res/raw/confetti_animation.json
  gradle/libs.versions.toml
Labels: enhancement

#283 PERA-2019 :: Add new UI changes for RegisterIntroFragment
  app/src/main/kotlin/com/algorand/android/ui/compose/theme/Color.kt
  app/src/main/kotlin/com/algorand/android/ui/compose/theme/PeraDarkColor.kt
  app/src/main/kotlin/com/algorand/android/ui/compose/theme/PeraLightColor.kt
  app/src/main/kotlin/com/algorand/android/ui/compose/typography/PeraTypography.kt
  app/src/main/kotlin/com/algorand/android/ui/compose/typography/PeraTypographyBody.kt
  app/src/main/kotlin/com/algorand/android/ui/compose/typography/PeraTypographyCaption.kt
  app/src/main/kotlin/com/algorand/android/ui/compose/typography/PeraTypographyFootnote.kt
  app/src/main/kotlin/com/algorand/android/ui/compose/typography/PeraTypographyTitle.kt
  app/src/main/kotlin/com/algorand/android/ui/compose/widget/GroupChoiceWidget.kt
  app/src/main/kotlin/com/algorand/android/ui/compose/widget/PeraFontFamily.kt
  app/src/main/kotlin/com/algorand/android/ui/compose/widget/icon/PeraIcon.kt
  app/src/main/kotlin/com/algorand/android/ui/compose/widget/text/PeraText.kt
  app/src/main/kotlin/com/algorand/android/ui/register/nameregistration/BaseNameRegistrationFragment.kt
  app/src/main/kotlin/com/algorand/android/ui/register/registerintro/RegisterIntroFragment.kt
  app/src/main/kotlin/com/algorand/android/usecase/IsOnHdWalletUseCase.kt
  app/src/main/res/layout/bottom_sheet_accounts_address_scan_action.xml
  app/src/main/res/values/strings.xml
Labels: enhancement

#285 PERA-1985 :: Fix rekey values in account status detail bottom nav
  app/src/main/kotlin/com/algorand/android/CoreActionsTabBarViewModel.kt
  app/src/main/kotlin/com/algorand/android/modules/accountdetail/accountstatusdetail/ui/decider/AccountStatusDetailPreviewDecider.kt
  app/src/main/kotlin/com/algorand/android/modules/accounts/lite/domain/model/AccountLite.kt
  app/src/main/kotlin/com/algorand/android/modules/accounts/lite/domain/usecase/GetAccountLitesFlowUseCase.kt
  app/src/main/kotlin/com/algorand/android/usecase/GetIsProductionBuildUseCase.kt
  app/src/main/res/values/strings.xml
Labels: bug

#289 PERA-2157 :: Call initialize when lifecycle state is created
  app/src/main/kotlin/com/algorand/android/CoreMainActivity.kt
  app/src/main/kotlin/com/algorand/android/MainActivity.kt
Labels: bug

#287 PERA-2145 :: Remove try-catch from AccountInformationRepository
  common-sdk/src/main/kotlin/com/algorand/wallet/account/info/data/repository/AccountInformationRepositoryImpl.kt
Labels: bug

#296 PERA-2038 :: Fix account search progress alignment issue
  app/src/main/kotlin/com/algorand/android/ui/compose/widget/AnimationLoader.kt
  app/src/main/res/layout/fragment_recover_with_passphrase.xml
  gradle/libs.versions.toml
Labels: bug

#297 PERA-2150 :: Update copies for hd account recover flow
  app/src/main/kotlin/com/algorand/android/customviews/RegisterTypeSelectionItem.kt
  app/src/main/kotlin/com/algorand/android/modules/onboarding/recoverypassphrase/info/ui/RecoverAccountInfoFragment.kt
  app/src/main/kotlin/com/algorand/android/ui/register/recoveraccounttypeselection/AccountRecoveryTypeSelectionFragment.kt
  app/src/main/kotlin/com/algorand/android/ui/register/recoveraccounttypeselection/AccountRecoveryTypeSelectionViewModel.kt
  app/src/main/res/layout/custom_register_type_selection.xml
  app/src/main/res/layout/fragment_account_recovery_type_selection.xml
  app/src/main/res/values/attrs.xml
  app/src/main/res/values/strings.xml
Labels: bug

#299 PERA-1773 :: Skip info screens after import accounts
  app/src/main/kotlin/com/algorand/android/modules/onboarding/pairledger/resultinfo/VerifyLedgerInfoFragment.kt
  app/src/main/kotlin/com/algorand/android/modules/onboarding/pairledger/resultinfo/VerifyLedgerInfoViewModel.kt
  app/src/main/kotlin/com/algorand/android/modules/onboarding/pairledger/verifyselectedaccount/ui/VerifyLedgerAddressFragment.kt
  app/src/main/kotlin/com/algorand/android/modules/onboarding/pairledger/verifyselectedaccount/ui/VerifyLedgerAddressViewModel.kt
  app/src/main/kotlin/com/algorand/android/modules/onboarding/recoverypassphrase/result/ui/RecoverAccountResultInfoFragment.kt
  app/src/main/kotlin/com/algorand/android/modules/onboarding/recoverypassphrase/result/ui/RecoverAccountResultInfoViewModel.kt
  app/src/main/kotlin/com/algorand/android/ui/rekeyedaccounts/hdkey/view/RecoverHdKeyRekeyedAccountSelectionFragment.kt
  app/src/main/kotlin/com/algorand/android/ui/rekeyedaccounts/viewmodel/RekeyedAccountSelectionViewModel.kt
  app/src/main/res/navigation/pair_ledger_navigation.xml
  app/src/main/res/navigation/recover_with_passphrase_navigation.xml
Labels: bug

#295 PERA-1962 :: Fix cards arbitrary signing for hd accounts
  app/src/main/kotlin/com/algorand/android/utils/walletconnect/WalletConnectArbitraryDataSignManager.kt
  app/src/main/res/values-night/colors.xml
  app/src/main/res/values/colors.xml
  common-sdk/src/main/kotlin/com/algorand/wallet/algosdk/transaction/sdk/SignHdKeyTransaction.kt
  common-sdk/src/main/kotlin/com/algorand/wallet/algosdk/transaction/sdk/SignHdKeyTransactionImpl.kt
Labels: bug

#301 PERA-1954 :: Add universal and ledger not supported warning to ASB
  app/src/main/res/layout/fragment_algorand_secure_backup_intro.xml
  app/src/main/res/values/strings.xml
Labels: enhancement

#302 PERA-2152 :: Create the new onboarding page for the first time users
  app/src/main/kotlin/com/algorand/android/CoreMainActivity.kt
  app/src/main/kotlin/com/algorand/android/CoreMainViewModel.kt
  app/src/main/kotlin/com/algorand/android/modules/tracking/core/BaseEventTracker.kt
  app/src/main/kotlin/com/algorand/android/modules/tracking/onboarding/BaseOnboardingEvenTracker.kt
  app/src/main/kotlin/com/algorand/android/ui/compose/widget/button/PeraButton.kt
  app/src/main/kotlin/com/algorand/android/ui/compose/widget/button/PeraButtonModifier.kt
  app/src/main/kotlin/com/algorand/android/ui/compose/widget/button/PeraButtonPreview.kt
  app/src/main/kotlin/com/algorand/android/ui/compose/widget/icon/PeraIcon.kt
  app/src/main/kotlin/com/algorand/android/ui/register/initialregisterintro/InitialRegisterIntroFragment.kt
  app/src/main/kotlin/com/algorand/android/ui/register/initialregisterintro/InitialRegisterIntroViewModel.kt
  app/src/main/kotlin/com/algorand/android/ui/register/registerintro/RegisterIntroFragment.kt
  app/src/main/res/navigation/initial_register_navigation.xml
  app/src/main/res/navigation/login_navigation.xml
  app/src/main/res/navigation/main_navigation.xml
  app/src/main/res/navigation/recovery_type_selection_navigation.xml
  app/src/main/res/values/strings.xml
Labels: enhancement

#303 PERA-2150 :: Update recovery type selection flow
  app/src/main/kotlin/com/algorand/android/modules/onboarding/recoverypassphrase/info/ui/RecoverAccountInfoFragment.kt
  app/src/main/kotlin/com/algorand/android/modules/onboarding/recoverypassphrase/info/ui/RecoveryAccountInfoViewModel.kt
  app/src/main/kotlin/com/algorand/android/modules/rekey/rekeytoledgeraccount/resultinfo/ui/RekeyToLedgerAccountVerifyInfoFragment.kt
  app/src/main/kotlin/com/algorand/android/modules/rekey/rekeytostandardaccount/resultinfo/ui/RekeyToStandardAccountVerifyInfoFragment.kt
  app/src/main/kotlin/com/algorand/android/modules/rekey/undorekey/resultinfo/ui/UndoRekeyVerifyInfoFragment.kt
  app/src/main/kotlin/com/algorand/android/ui/common/warningconfirmation/BackupInfoFragment.kt
  app/src/main/kotlin/com/algorand/android/ui/common/warningconfirmation/WriteDownInfoFragment.kt
  app/src/main/kotlin/com/algorand/android/ui/compose/theme/Color.kt
  app/src/main/kotlin/com/algorand/android/ui/compose/theme/PeraDarkColor.kt
  app/src/main/kotlin/com/algorand/android/ui/compose/theme/PeraLightColor.kt
  app/src/main/kotlin/com/algorand/android/ui/compose/widget/GroupChoiceWidget.kt
  app/src/main/kotlin/com/algorand/android/ui/compose/widget/PeraCard.kt
  app/src/main/kotlin/com/algorand/android/ui/compose/widget/button/PeraButton.kt
  app/src/main/kotlin/com/algorand/android/ui/compose/widget/text/PeraText.kt
  app/src/main/kotlin/com/algorand/android/ui/compose/widget/text/PeraTextPreview.kt
  app/src/main/kotlin/com/algorand/android/ui/lockpreference/BiometricAuthenticationEnabledFragment.kt
  app/src/main/kotlin/com/algorand/android/ui/lockpreference/BiometricRegistrationFragment.kt
  app/src/main/kotlin/com/algorand/android/ui/lockpreference/ChoosePasswordInfoFragment.kt
  app/src/main/kotlin/com/algorand/android/ui/onboarding/recoverypassphrase/importregisteredaddresses/RecoverRegisteredAccountsScreen.kt
  app/src/main/kotlin/com/algorand/android/ui/register/createaccount/passphraseverified/PassphraseVerifiedInfoFragment.kt
  app/src/main/kotlin/com/algorand/android/ui/register/recoveraccounttypeselection/AccountRecoveryTypeSelectionFragment.kt
  app/src/main/kotlin/com/algorand/android/ui/register/recoveraccounttypeselection/AccountRecoveryTypeSelectionViewModel.kt
  app/src/main/kotlin/com/algorand/android/ui/register/registerintro/RegisterIntroFragment.kt
  app/src/main/kotlin/com/algorand/android/ui/register/watch/WatchAccountInfoFragment.kt
  app/src/main/kotlin/com/algorand/android/ui/register/watch/result/WatchAccountResultInfoFragment.kt
  app/src/main/kotlin/com/algorand/android/utils/browser/BrowserUtils.kt
  app/src/main/res/layout/fragment_account_recovery_type_selection.xml
  app/src/main/res/layout/fragment_web_import_intro.xml
  app/src/main/res/navigation/recovery_type_selection_navigation.xml
  app/src/main/res/values/strings.xml
  gradle/libs.versions.toml
Labels: enhancement

#306 PERA-1839 :: Remove seed when its last derived address is removed
  common-sdk/src/main/kotlin/com/algorand/wallet/account/local/data/database/dao/HdKeyDao.kt
  common-sdk/src/main/kotlin/com/algorand/wallet/account/local/data/repository/HdKeyAccountRepositoryImpl.kt
  common-sdk/src/main/kotlin/com/algorand/wallet/account/local/domain/repository/HdKeyAccountRepository.kt
  common-sdk/src/main/kotlin/com/algorand/wallet/account/local/domain/usecase/DeleteLocalAccountUseCase.kt
  common-sdk/src/test/kotlin/com/algorand/wallet/account/local/domain/usecase/DeleteLocalAccountUseCaseTest.kt
Labels: enhancement

#311 PERA-2253 :: Use simple account detail for rekeyed addresses
  app/src/main/kotlin/com/algorand/android/modules/onboarding/recoverypassphrase/enterpassphrase/ui/usecase/RecoverWithPassphrasePreviewUseCase.kt
  app/src/main/kotlin/com/algorand/android/modules/onboarding/recoverypassphrase/rekeyedaccountselection/information/ui/usecase/RekeyedAccountInformationPreviewUseCase.kt
  app/src/main/kotlin/com/algorand/android/ui/onboarding/recoverypassphrase/importregisteredaddresses/RecoverRegisteredAccountsViewModel.kt
Labels: bug

#313 PERA-2201 :: Remove toolbar for discover v5
  app/src/main/kotlin/com/algorand/android/discover/home/ui/DiscoverHomeFragment.kt
  app/src/main/kotlin/com/algorand/android/discover/home/ui/DiscoverHomeViewModel.kt
  app/src/main/res/layout/fragment_discover_home.xml
  app/src/main/res/values/dimens.xml
  common-sdk/src/main/kotlin/com/algorand/wallet/remoteconfig/domain/usecase/IsFeatureToggleEnabled.kt
  gradle/libs.versions.toml
Labels: enhancement
