Repository perawallet/pera-android, pull requests merged in 2025-01, with the labels that each got.

#96 PERA-1209 :: Handle new discover, staking and cards deeplinks
  app/build.gradle
  app/src/main/java/com/algorand/android/CoreActionsTabBarViewModel.kt
  app/src/main/java/com/algorand/android/MainActivity.kt
  app/src/main/java/com/algorand/android/modules/card/CardsViewModel.kt
  app/src/main/java/com/algorand/android/modules/deeplink/ui/DeeplinkHandler.kt
  app/src/main/java/com/algorand/android/modules/qrscanning/BaseQrScannerFragment.kt
  app/src/main/java/com/algorand/android/modules/staking/StakingViewModel.kt
  app/src/main/res/navigation/home_navigation.xml
  wallet-sdk/src/androidUnitTest/kotlin/com/algorand/common/deeplink/CreateDeepLinkImplTest.kt
  wallet-sdk/src/androidUnitTest/kotlin/com/algorand/common/deeplink/parser/ParseDeepLinkPayloadImplTest.kt
  wallet-sdk/src/commonMain/kotlin/com/algorand/common/deeplink/builder/CardsDeepLinkBuilder.kt
  wallet-sdk/src/commonMain/kotlin/com/algorand/common/deeplink/builder/DiscoverDeepLinkBuilder.kt
  wallet-sdk/src/commonMain/kotlin/com/algorand/common/deeplink/builder/StakingDeepLinkBuilder.kt
  wallet-sdk/src/commonMain/kotlin/com/algorand/common/deeplink/di/DeepLinkKoinModule.kt
  wallet-sdk/src/commonMain/kotlin/com/algorand/common/deeplink/model/DeepLink.kt
  wallet-sdk/src/commonMain/kotlin/com/algorand/common/deeplink/model/DeepLinkPayload.kt
  wallet-sdk/src/commonMain/kotlin/com/algorand/common/deeplink/parser/CreateDeepLinkImpl.kt
  wallet-sdk/src/commonMain/kotlin/com/algorand/common/deeplink/parser/ParseDeepLinkPayloadImpl.kt
Labels: enhancement

#98 PERA-879 :: Allow users to backup all the accounts except ledger accounts
  app/src/main/java/com/algorand/android/models/AccountIconResource.kt
  app/src/main/java/com/algorand/android/modules/accounticon/ui/usecase/CreateAccountIconDrawableUseCase.kt
  app/src/main/java/com/algorand/android/modules/asb/importbackup/accountrestoreresult/ui/usecase/AsbAccountRestoreResultPreviewUseCase.kt
  app/src/main/java/com/algorand/android/modules/asb/importbackup/accountselection/ui/usecase/AsbImportAccountSelectionPreviewUseCase.kt
  app/src/main/java/com/algorand/android/modules/asb/importbackup/accountselection/utils/AsbAccountImportParser.kt
  app/src/main/java/com/algorand/android/modules/asb/util/AlgorandSecureBackupUtils.kt
  app/src/main/java/com/algorand/android/modules/backupprotocol/domain/usecase/CreateBackupProtocolPayloadUseCase.kt
  app/src/main/java/com/algorand/android/modules/backupprotocol/util/BackupProtocolUtils.kt
  app/src/main/java/com/algorand/android/modules/basemultipleaccountselection/ui/usecase/BaseMultipleAccountSelectionPreviewUseCase.kt
  app/src/main/java/com/algorand/android/modules/baseresult/ui/usecase/BaseResultPreviewUseCase.kt
Labels: enhancement

#92 PERA-1348 :: Add in architecture related ER diagrams designed in mermaid
  ARCHITECTURE.md
  mermaid/database_address.png
  mermaid/database_pera.png
  mermaid/polling.png
Labels: enhancement

#101 PERA-1159 :: Handle account selection automatically in ARC-78 flow
  app/src/main/java/com/algorand/android/MainActivity.kt
  app/src/main/java/com/algorand/android/MainViewModel.kt
  app/src/main/java/com/algorand/android/modules/keyreg/domain/usecase/KeyRegAccountSelectionPreviewUseCase.kt
  app/src/main/java/com/algorand/android/modules/keyreg/ui/KeyRegAccountSelectionFragment.kt
  app/src/main/java/com/algorand/android/modules/keyreg/ui/KeyRegAccountSelectionViewModel.kt
  app/src/main/java/com/algorand/android/modules/keyreg/ui/KeyRegTransactionViewModel.kt
  app/src/main/java/com/algorand/android/modules/keyreg/ui/components/KeyRegTable.kt
  app/src/main/java/com/algorand/android/modules/keyreg/ui/mapper/KeyRegTransactionPreviewMapper.kt
  app/src/main/java/com/algorand/android/modules/keyreg/ui/model/KeyRegTransactionPreview.kt
  app/src/main/java/com/algorand/android/modules/qrscanning/BaseQrScannerFragment.kt
  app/src/main/java/com/algorand/android/modules/qrscanning/QrScannerViewModel.kt
  app/src/main/java/com/algorand/android/usecase/GetLocalAccountsUseCase.kt
  app/src/main/res/navigation/home_navigation.xml
  app/src/main/res/values/strings.xml
  gradle/libs.versions.toml
Labels: enhancement

#102 PERA-1364 :: Fix cards flag to show on staging testnet builds
  app/src/main/java/com/algorand/android/CoreActionsTabBarViewModel.kt
  app/src/main/java/com/algorand/android/MainActivity.kt
  app/src/main/java/com/algorand/android/usecase/GetIsProductionReleaseUseCase.kt
Labels: bug

#105 PERA-1432 :: Fix staking menu item layout issue
  app/src/main/res/layout/custom_list_new_menu_item_view.xml
  gradle/libs.versions.toml
Labels: bug

#100 PERA-1382 :: Add cache initialization flowchart
  ARCHITECTURE.md
  mermaid/database_address.png
  mermaid/database_pera.png
  mermaid/er-diagrams/database_address.png
  mermaid/er-diagrams/database_pera.png
  mermaid/flowcharts/cache_initialization.png
  mermaid/flowcharts/flowchart_app_layers.png
  mermaid/flowcharts/polling.png
Labels: documentation

#106 PERA-1471 :: Upgrade AlgoSDK to latest version (2.6.0)
  gradle/libs.versions.toml
Labels: chore

#114 PERA-1491 :: Add bouncycastle init to AlgoSdkUtilsImpl.kt
  common-sdk/src/main/kotlin/com/algorand/wallet/algosdk/AlgoSdkUtilsImpl.kt
Labels: bug

#117 PERA-1491 :: Fix proguard issue for deeplink due to package name change
  app/proguard-rules.pro
Labels: bug
