Repository perawallet/pera-android, pull requests merged in 2025-06, with the labels that each got.

#292 PERA-2169 :: Add Algo25 create wallet button in dev settings
  app/src/main/kotlin/com/algorand/android/ui/settings/developersettings/DeveloperSettingsFragment.kt
  app/src/main/kotlin/com/algorand/android/ui/settings/developersettings/DeveloperSettingsViewModel.kt
  app/src/main/res/layout/fragment_developer_settings.xml
  app/src/main/res/navigation/home_navigation.xml
  app/src/main/res/values/strings.xml
Labels: enhancement, external contribution

#315 PERA-2281 :: Compose Preview Screenshot Testing
  app/build.gradle
  app/src/screenshotTest/kotlin/com/algorand/android/PeraButtonScreenshotTest.kt
  gradle.properties
  gradle/libs.versions.toml
Labels: enhancement, external contribution, draft

#327 PERA-2248 :: Add horizontal alignment parameter to the PeraButton
  app/src/main/kotlin/com/algorand/android/ui/compose/widget/button/PeraButton.kt
  app/src/main/kotlin/com/algorand/android/ui/compose/widget/button/PeraButtonModifier.kt
  app/src/main/kotlin/com/algorand/android/ui/register/initialregisterintro/InitialRegisterIntroFragment.kt
Labels: bug

#336 PERA-2394 :: Clear seed table index when all items are deleted
  common-sdk/src/main/kotlin/com/algorand/wallet/account/local/data/database/dao/HdSeedDao.kt
  common-sdk/src/main/kotlin/com/algorand/wallet/account/local/data/repository/HdSeedRepositoryImpl.kt
  common-sdk/src/test/kotlin/com/algorand/wallet/account/local/data/repository/HdSeedRepositoryImplTest.kt
  gradle/libs.versions.toml
Labels: bug

#339 Released hot fixes
  app/src/main/kotlin/com/algorand/android/ui/onboarding/creation/mapper/DefaultAccountCreationHdKeyTypeMapper.kt
  common-sdk/src/main/kotlin/com/algorand/wallet/account/local/data/database/dao/HdSeedDao.kt
  common-sdk/src/main/kotlin/com/algorand/wallet/account/local/data/repository/HdSeedRepositoryImpl.kt
  common-sdk/src/test/kotlin/com/algorand/wallet/account/local/data/repository/HdSeedRepositoryImplTest.kt
  gradle/libs.versions.toml
Labels: bug

#338 PERA-2361 :: Get auth address from webview in discover home page
  app/src/main/kotlin/com/algorand/android/discover/home/ui/DiscoverHomeFragment.kt
  app/src/main/kotlin/com/algorand/android/discover/home/ui/DiscoverHomeViewModel.kt
  app/src/main/kotlin/com/algorand/android/discover/home/ui/model/DiscoverHomePreview.kt
Labels: enhancement
