Repository perawallet/pera-android, pull requests merged in 2025-02, with the labels that each got.

#123 PERA-1014 :: Upgrade to support Java 21
  .github/workflows/android-app-tests.yml
  app/build.gradle
  app/checkstyle.xml
  app/quality.gradle
  common-sdk/build.gradle.kts
  composeTestApp/build.gradle.kts
  detekt-config.yml
  gradle/libs.versions.toml
  test-utils/build.gradle.kts
  wallet-sdk/build.gradle.kts
Labels: chore

#126 PERA-1555 :: Add BrowserStack to readme
  README.md
Labels: documentation

#107 PERA-1474 :: Update app layers diagram
  ARCHITECTURE.md
  mermaid/er-diagrams/database_address.png
  mermaid/er-diagrams/database_pera.png
  mermaid/flowcharts/flowchart_app_layers.png
  mermaid/flowcharts/flowchart_cache_initialization.png
  mermaid/flowcharts/flowchart_polling.png
Labels: documentation, draft

#128 PERA-1560 :: Add BrowserStack Github integration
  .github/workflows/browserstack-app-tests.yml
  app/build.gradle
  app/src/androidTest/kotlin/com/algorand/android/DatabaseMigrationUnitTest.kt
  app/src/main/kotlin/com/algorand/android/exceptions/RetrofitErrorHandler.kt
  common-sdk/build.gradle.kts
  gradle/libs.versions.toml
Labels: gitops

#129 PERA-1572 :: Switch to saving entropy instead of Mnemonic
  ARCHITECTURE.md
  common-sdk/src/main/kotlin/com/algorand/wallet/account/local/data/database/model/HdSeedEntity.kt
  common-sdk/src/main/kotlin/com/algorand/wallet/account/local/domain/model/HdSeed.kt
  common-sdk/src/main/kotlin/com/algorand/wallet/algosdk/model/HdAccount.kt
  common-sdk/src/main/kotlin/com/algorand/wallet/algosdk/transaction/sdk/AlgoAccountSdkImpl.kt
  common-sdk/src/main/kotlin/com/algorand/wallet/encryption/EntropyEncryptionManager.kt
  common-sdk/src/main/kotlin/com/algorand/wallet/encryption/EntropyEncryptionManagerImpl.kt
  common-sdk/src/main/kotlin/com/algorand/wallet/encryption/di/EncryptionModule.kt
Labels: enhancement

#125 PERA-1057 :: Change staging urls for staging mainnet builds
  app/build.gradle
  app/src/main/kotlin/com/algorand/android/CoreActionsTabBarViewModel.kt
  app/src/main/kotlin/com/algorand/android/CoreMainActivity.kt
  app/src/main/kotlin/com/algorand/android/MainActivity.kt
  app/src/main/kotlin/com/algorand/android/core/BaseFragment.kt
  app/src/main/kotlin/com/algorand/android/customviews/CoreActionsTabBarView.kt
  app/src/main/kotlin/com/algorand/android/modules/dapp/meld/ui/intro/MeldIntroViewModel.kt
Labels: enhancement

#130 PERA-1517 :: Add in heartbeat txn type
  app/src/main/kotlin/com/algorand/android/modules/algosdk/data/mapper/rawtransaction/RawTransactionTypeDTODecider.kt
  app/src/main/kotlin/com/algorand/android/modules/algosdk/data/model/rawtransaction/RawTransactionTypePayload.kt
  app/src/main/kotlin/com/algorand/android/modules/algosdk/domain/mapper/rawtransaction/RawTransactionTypeDTODecider.kt
  app/src/main/kotlin/com/algorand/android/modules/algosdk/domain/model/RawTransactionType.kt
  app/src/main/kotlin/com/algorand/android/modules/algosdk/domain/model/dto/RawTransactionTypeDTO.kt
  app/src/main/kotlin/com/algorand/android/modules/transaction/common/data/mapper/TransactionTypeDTOMapper.kt
  app/src/main/kotlin/com/algorand/android/modules/transaction/common/data/model/TransactionTypeResponse.kt
  app/src/main/kotlin/com/algorand/android/modules/transaction/common/domain/model/TransactionDTO.kt
  app/src/main/kotlin/com/algorand/android/modules/transaction/common/domain/model/TransactionTypeDTO.kt
  app/src/main/kotlin/com/algorand/android/modules/transaction/detail/domain/mapper/BaseTransactionDetailMapper.kt
  app/src/main/kotlin/com/algorand/android/modules/transaction/detail/domain/model/BaseTransactionDetail.kt
  app/src/main/kotlin/com/algorand/android/modules/transaction/detail/domain/usecase/BaseTransactionDetailPreviewUseCase.kt
  app/src/main/kotlin/com/algorand/android/modules/transaction/detail/domain/usecase/GetTransactionDetailUseCase.kt
  app/src/main/kotlin/com/algorand/android/modules/transaction/detail/domain/usecase/InnerTransactionDetailPreviewUseCase.kt
  app/src/main/kotlin/com/algorand/android/modules/transactionhistory/domain/mapper/BaseTransactionMapper.kt
  app/src/main/kotlin/com/algorand/android/modules/transactionhistory/domain/model/BaseTransaction.kt
  app/src/main/kotlin/com/algorand/android/modules/transactionhistory/domain/usecase/TransactionHistoryUseCase.kt
  app/src/main/kotlin/com/algorand/android/modules/transactionhistory/ui/mapper/TransactionItemMapper.kt
  app/src/main/kotlin/com/algorand/android/modules/transactionhistory/ui/model/BaseTransactionItem.kt
  app/src/main/kotlin/com/algorand/android/modules/transactionhistory/ui/usecase/BaseTransactionPreviewUseCase.kt
  app/src/main/kotlin/com/algorand/android/modules/walletconnect/ui/mapper/WalletConnectTransactionMapper.kt
  app/src/main/res/values/donottranslate.xml
  common-sdk/src/main/kotlin/com/algorand/wallet/algosdk/transaction/mapper/RawTransactionTypeMapperImpl.kt
  common-sdk/src/main/kotlin/com/algorand/wallet/algosdk/transaction/model/RawTransactionType.kt
  common-sdk/src/main/kotlin/com/algorand/wallet/algosdk/transaction/model/payload/RawTransactionTypePayload.kt
  common-sdk/src/test/kotlin/com/algorand/wallet/algosdk/transaction/mapper/RawTransactionTypeMapperImplTest.kt
Labels: enhancement

#136 PERA-1607 :: Migrate swap flow
  app/src/main/kotlin/com/algorand/android/core/transaction/external/ExternalTransactionSignManager.kt
  app/src/main/kotlin/com/algorand/android/modules/swap/assetselection/fromasset/ui/usecase/SwapFromAssetSelectionPreviewUseCase.kt
  app/src/main/kotlin/com/algorand/android/modules/swap/assetselection/toasset/ui/usecase/SwapToAssetSelectionPreviewUseCase.kt
  app/src/main/kotlin/com/algorand/android/modules/swap/assetswap/ui/AssetSwapFragment.kt
  app/src/main/kotlin/com/algorand/android/modules/swap/assetswap/ui/AssetSwapViewModel.kt
  app/src/main/kotlin/com/algorand/android/modules/swap/assetswap/ui/mapper/AssetSwapPreviewMapper.kt
  app/src/main/kotlin/com/algorand/android/modules/swap/assetswap/ui/model/AssetSwapPreview.kt
  app/src/main/kotlin/com/algorand/android/modules/swap/assetswap/ui/usecase/AssetSwapCreateQuotePreviewUseCase.kt
  app/src/main/kotlin/com/algorand/android/modules/swap/assetswap/ui/usecase/AssetSwapInitialPreviewUseCase.kt
  app/src/main/kotlin/com/algorand/android/modules/swap/assetswap/ui/usecase/AssetSwapPreviewAssetDetailUseCase.kt
  app/src/main/kotlin/com/algorand/android/modules/swap/assetswap/ui/usecase/AssetSwapPreviewUseCase.kt
  app/src/main/kotlin/com/algorand/android/modules/swap/assetswap/ui/usecase/AssetSwapSwitchButtonStatusUseCase.kt
  app/src/main/kotlin/com/algorand/android/modules/swap/assetswap/ui/usecase/GetPercentageCalculatedBalanceForSwapUseCase.kt
  app/src/main/kotlin/com/algorand/android/modules/swap/assetswap/ui/utils/SwapBalanceErrorProvider.kt
  app/src/main/kotlin/com/algorand/android/modules/swap/confirmswap/domain/SwapTransactionSignManager.kt
  app/src/main/kotlin/com/algorand/android/modules/swap/transactionsummary/ui/adapter/SwapAccountItemViewHolder.kt
  app/src/main/kotlin/com/algorand/android/modules/swap/transactionsummary/ui/mapper/BaseSwapTransactionSummaryItemMapper.kt
  app/src/main/kotlin/com/algorand/android/modules/swap/transactionsummary/ui/model/BaseSwapTransactionSummaryItem.kt
  app/src/main/kotlin/com/algorand/android/modules/swap/transactionsummary/ui/usecase/SwapTransactionSummaryPreviewUseCase.kt
  app/src/main/kotlin/com/algorand/android/usecase/CheckUserHasAssetBalanceUseCase.kt
  common-sdk/src/main/kotlin/com/algorand/wallet/account/info/data/cache/AccountInformationErrorCache.kt
  common-sdk/src/main/kotlin/com/algorand/wallet/account/info/data/cache/AccountInformationErrorCacheImpl.kt
  common-sdk/src/main/kotlin/com/algorand/wallet/account/info/data/database/dao/AccountInformationDao.kt
  common-sdk/src/main/kotlin/com/algorand/wallet/account/info/data/mapper/AccountInformationErrorEntityMapperImpl.kt
  common-sdk/src/main/kotlin/com/algorand/wallet/account/info/data/repository/AccountInformationCacheHelperImpl.kt
  common-sdk/src/main/kotlin/com/algorand/wallet/account/info/data/repository/AccountInformationRepositoryImpl.kt
  common-sdk/src/main/kotlin/com/algorand/wallet/account/info/di/AccountInformationModule.kt
  common-sdk/src/main/kotlin/com/algorand/wallet/account/info/domain/repository/AccountInformationRepository.kt
  common-sdk/src/main/kotlin/com/algorand/wallet/account/info/domain/usecase/AccountInformationUseCases.kt
  common-sdk/src/main/kotlin/com/algorand/wallet/account/info/domain/usecase/IsAccountCachedSuccessfullyUseCase.kt
  common-sdk/src/main/kotlin/com/algorand/wallet/account/info/domain/usecase/IsAssetOwnedByAccountUseCase.kt
  common-sdk/src/main/kotlin/com/algorand/wallet/account/info/domain/usecase/IsThereAnyCachedErrorAccountUseCase.kt
  common-sdk/src/main/kotlin/com/algorand/wallet/account/info/domain/usecase/IsThereAnyCachedSuccessAccountUseCase.kt
  common-sdk/src/main/kotlin/com/algorand/wallet/block/domain/usecase/ShouldUpdateAccountCacheUseCase.kt
  common-sdk/src/test/kotlin/com/algorand/wallet/account/info/data/cache/AccountInformationErrorCacheImplTest.kt
  common-sdk/src/test/kotlin/com/algorand/wallet/account/info/data/mapper/AccountInformationErrorEntityMapperImplTest.kt
  common-sdk/src/test/kotlin/com/algorand/wallet/account/info/domain/usecase/IsAccountCachedSuccessfullyUseCaseTest.kt
  common-sdk/src/test/kotlin/com/algorand/wallet/account/info/domain/usecase/IsThereAnyCachedErrorAccountUseCaseTest.kt
  common-sdk/src/test/kotlin/com/algorand/wallet/account/info/domain/usecase/IsThereAnyCachedSuccessAccountUseCaseTest.kt
Labels: epic

#121 PERA-1545 :: Compose migration of BaseInfoFragment
  .github/workflows/browserstack-app-tests.yml
  app/src/main/kotlin/com/algorand/android/core/BaseFragment.kt
  app/src/main/kotlin/com/algorand/android/modules/onboarding/pairledger/resultinfo/VerifyLedgerInfoFragment.kt
  app/src/main/kotlin/com/algorand/android/modules/onboarding/recoverypassphrase/info/ui/RecoverAccountInfoFragment.kt
  app/src/main/kotlin/com/algorand/android/modules/onboarding/recoverypassphrase/result/ui/RecoverAccountResultInfoFragment.kt
  app/src/main/kotlin/com/algorand/android/modules/rekey/rekeytoledgeraccount/resultinfo/ui/RekeyToLedgerAccountVerifyInfoFragment.kt
  app/src/main/kotlin/com/algorand/android/modules/rekey/rekeytostandardaccount/resultinfo/ui/RekeyToStandardAccountVerifyInfoFragment.kt
  app/src/main/kotlin/com/algorand/android/modules/rekey/undorekey/resultinfo/ui/UndoRekeyVerifyInfoFragment.kt
  app/src/main/kotlin/com/algorand/android/ui/common/BaseInfoFragment.kt
  app/src/main/kotlin/com/algorand/android/ui/common/warningconfirmation/BackupInfoFragment.kt
  app/src/main/kotlin/com/algorand/android/ui/common/warningconfirmation/WriteDownInfoFragment.kt
  app/src/main/kotlin/com/algorand/android/ui/compose/theme/PeraColor.kt
  app/src/main/kotlin/com/algorand/android/ui/compose/theme/PeraTheme.kt
  app/src/main/kotlin/com/algorand/android/ui/compose/widget/PeraButton.kt
  app/src/main/kotlin/com/algorand/android/ui/compose/widget/PeraFontFamily.kt
  app/src/main/kotlin/com/algorand/android/ui/compose/widget/PeraIcon.kt
  app/src/main/kotlin/com/algorand/android/ui/compose/widget/PeraText.kt
  app/src/main/kotlin/com/algorand/android/ui/lockpreference/BiometricAuthenticationEnabledFragment.kt
  app/src/main/kotlin/com/algorand/android/ui/lockpreference/BiometricRegistrationFragment.kt
  app/src/main/kotlin/com/algorand/android/ui/lockpreference/ChoosePasswordInfoFragment.kt
  app/src/main/kotlin/com/algorand/android/ui/register/createaccount/passphraseverified/PassphraseVerifiedInfoFragment.kt
  app/src/main/kotlin/com/algorand/android/ui/register/createaccount/result/CreateAccountResultInfoFragment.kt
  app/src/main/kotlin/com/algorand/android/ui/register/watch/WatchAccountInfoFragment.kt
  app/src/main/kotlin/com/algorand/android/ui/register/watch/result/WatchAccountResultInfoFragment.kt
  app/src/main/res/layout/fragment_base_info.xml
  app/src/main/res/navigation/backup_passphrase_account_name_navigation.xml
  app/src/main/res/navigation/backup_passphrase_info_navigation.xml
  app/src/main/res/navigation/backup_passphrase_navigation.xml
  app/src/main/res/navigation/lock_preference_navigation.xml
  app/src/main/res/navigation/login_navigation.xml
  app/src/main/res/navigation/pair_ledger_navigation.xml
  app/src/main/res/navigation/recover_with_passphrase_navigation.xml
  app/src/main/res/navigation/register_watch_account_navigation.xml
  app/src/main/res/navigation/rekey_to_ledger_account_navigation.xml
  app/src/main/res/navigation/rekey_to_standard_account_navigation.xml
  app/src/main/res/navigation/rekey_undo_navigation.xml
  detekt-config.yml
  gradle/libs.versions.toml
Labels: enhancement, external contribution

#137 PERA-1619 :: Upgrade AlgoSDK and bucket dependencies to groups in toml file
  .github/workflows/browserstack-app-tests.yml
  build.gradle.kts
  gradle/libs.versions.toml
Labels: chore

#144 PERA-1651 :: Remove pull_request trigger in browerstack job
  .github/workflows/browserstack-app-tests.yml
  .github/workflows/cla.yml
  app/src/test/kotlin/com/algorand/android/modules/algosdk/domain/mapper/TransactionParametersResponseMapperImplTest.kt
Labels: gitops

#148 PERA-1627 :: Replace rekeyed account functions in AccountDetailUseCase with common sdk functions
  app/src/main/kotlin/com/algorand/android/modules/accountdetail/removeaccount/ui/RemoveAccountConfirmationViewModel.kt
  app/src/main/kotlin/com/algorand/android/modules/accountdetail/removeaccount/ui/usecase/RemoveAccountConfirmationPreviewUseCase.kt
  app/src/main/kotlin/com/algorand/android/usecase/AccountDetailUseCase.kt
  app/src/test/kotlin/com/algorand/android/modules/keyreg/domain/usecase/CreateKeyRegTransactionUseCaseTest.kt
  common-sdk/src/main/kotlin/com/algorand/wallet/account/detail/di/AccountDetailModule.kt
  common-sdk/src/main/kotlin/com/algorand/wallet/account/detail/domain/usecase/AccountDetailUseCases.kt
  common-sdk/src/main/kotlin/com/algorand/wallet/account/detail/domain/usecase/GetLocalRekeyedAccountCountUseCase.kt
  common-sdk/src/main/kotlin/com/algorand/wallet/account/info/data/database/dao/AccountInformationDao.kt
  common-sdk/src/main/kotlin/com/algorand/wallet/account/info/data/repository/AccountInformationRepositoryImpl.kt
  common-sdk/src/main/kotlin/com/algorand/wallet/account/info/domain/repository/AccountInformationRepository.kt
  common-sdk/src/main/kotlin/com/algorand/wallet/account/local/data/database/dao/Algo25Dao.kt
  common-sdk/src/main/kotlin/com/algorand/wallet/account/local/data/database/dao/HdKeyDao.kt
  common-sdk/src/main/kotlin/com/algorand/wallet/account/local/data/database/dao/LedgerBleDao.kt
  common-sdk/src/main/kotlin/com/algorand/wallet/account/local/data/database/dao/NoAuthDao.kt
  common-sdk/src/main/kotlin/com/algorand/wallet/account/local/data/repository/Algo25AccountRepositoryImpl.kt
  common-sdk/src/main/kotlin/com/algorand/wallet/account/local/data/repository/HdKeyAccountRepositoryImpl.kt
  common-sdk/src/main/kotlin/com/algorand/wallet/account/local/data/repository/LedgerBleAccountRepositoryImpl.kt
  common-sdk/src/main/kotlin/com/algorand/wallet/account/local/data/repository/NoAuthAccountRepositoryImpl.kt
  common-sdk/src/main/kotlin/com/algorand/wallet/account/local/di/LocalAccountsModule.kt
  common-sdk/src/main/kotlin/com/algorand/wallet/account/local/domain/model/LocalAccount.kt
  common-sdk/src/main/kotlin/com/algorand/wallet/account/local/domain/repository/Algo25AccountRepository.kt
  common-sdk/src/main/kotlin/com/algorand/wallet/account/local/domain/repository/HdKeyAccountRepository.kt
  common-sdk/src/main/kotlin/com/algorand/wallet/account/local/domain/repository/LedgerBleAccountRepository.kt
  common-sdk/src/main/kotlin/com/algorand/wallet/account/local/domain/repository/NoAuthAccountRepository.kt
  common-sdk/src/main/kotlin/com/algorand/wallet/account/local/domain/usecase/GetLocalAccountsAddressesUseCase.kt
  common-sdk/src/main/kotlin/com/algorand/wallet/account/local/domain/usecase/LocalAccountUseCases.kt
  common-sdk/src/test/kotlin/com/algorand/wallet/account/core/domain/usecase/GetLocalAccountsAddressesUseCaseTest.kt
  common-sdk/src/test/kotlin/com/algorand/wallet/account/detail/domain/usecase/GetLocalRekeyedAccountCountUseCaseTest.kt
  common-sdk/src/test/kotlin/com/algorand/wallet/account/info/data/repository/AccountInformationRepositoryImplTest.kt
  common-sdk/src/test/kotlin/com/algorand/wallet/account/local/data/repository/Algo25AccountRepositoryImplTest.kt
  common-sdk/src/test/kotlin/com/algorand/wallet/account/local/data/repository/HdKeyAccountRepositoryImplTest.kt
  common-sdk/src/test/kotlin/com/algorand/wallet/account/local/data/repository/LedgerBleAccountRepositoryImplTest.kt
  common-sdk/src/test/kotlin/com/algorand/wallet/account/local/data/repository/NoAuthAccountRepositoryImplTest.kt
Labels: epic

#152 PERA-1627 :: Create rekeyed account count and addresses use cases
  common-sdk/src/main/kotlin/com/algorand/wallet/account/detail/di/AccountDetailModule.kt
  common-sdk/src/main/kotlin/com/algorand/wallet/account/detail/domain/usecase/AccountDetailUseCases.kt
  common-sdk/src/main/kotlin/com/algorand/wallet/account/detail/domain/usecase/GetLocalRekeyedAccountCountUseCase.kt
  common-sdk/src/main/kotlin/com/algorand/wallet/account/info/data/database/dao/AccountInformationDao.kt
  common-sdk/src/main/kotlin/com/algorand/wallet/account/info/data/repository/AccountInformationRepositoryImpl.kt
  common-sdk/src/main/kotlin/com/algorand/wallet/account/info/domain/repository/AccountInformationRepository.kt
  common-sdk/src/main/kotlin/com/algorand/wallet/account/local/data/database/dao/Algo25Dao.kt
  common-sdk/src/main/kotlin/com/algorand/wallet/account/local/data/database/dao/HdKeyDao.kt
  common-sdk/src/main/kotlin/com/algorand/wallet/account/local/data/database/dao/LedgerBleDao.kt
  common-sdk/src/main/kotlin/com/algorand/wallet/account/local/data/database/dao/NoAuthDao.kt
  common-sdk/src/main/kotlin/com/algorand/wallet/account/local/data/repository/Algo25AccountRepositoryImpl.kt
  common-sdk/src/main/kotlin/com/algorand/wallet/account/local/data/repository/HdKeyAccountRepositoryImpl.kt
  common-sdk/src/main/kotlin/com/algorand/wallet/account/local/data/repository/LedgerBleAccountRepositoryImpl.kt
  common-sdk/src/main/kotlin/com/algorand/wallet/account/local/data/repository/NoAuthAccountRepositoryImpl.kt
  common-sdk/src/main/kotlin/com/algorand/wallet/account/local/di/LocalAccountsModule.kt
  common-sdk/src/main/kotlin/com/algorand/wallet/account/local/domain/model/LocalAccount.kt
  common-sdk/src/main/kotlin/com/algorand/wallet/account/local/domain/repository/Algo25AccountRepository.kt
  common-sdk/src/main/kotlin/com/algorand/wallet/account/local/domain/repository/HdKeyAccountRepository.kt
  common-sdk/src/main/kotlin/com/algorand/wallet/account/local/domain/repository/LedgerBleAccountRepository.kt
  common-sdk/src/main/kotlin/com/algorand/wallet/account/local/domain/repository/NoAuthAccountRepository.kt
  common-sdk/src/main/kotlin/com/algorand/wallet/account/local/domain/usecase/GetLocalAccountsAddressesUseCase.kt
  common-sdk/src/main/kotlin/com/algorand/wallet/account/local/domain/usecase/LocalAccountUseCases.kt
  common-sdk/src/test/kotlin/com/algorand/wallet/account/core/domain/usecase/GetLocalAccountsAddressesUseCaseTest.kt
  common-sdk/src/test/kotlin/com/algorand/wallet/account/detail/domain/usecase/GetLocalRekeyedAccountCountUseCaseTest.kt
  common-sdk/src/test/kotlin/com/algorand/wallet/account/info/data/repository/AccountInformationRepositoryImplTest.kt
  common-sdk/src/test/kotlin/com/algorand/wallet/account/local/data/repository/Algo25AccountRepositoryImplTest.kt
  common-sdk/src/test/kotlin/com/algorand/wallet/account/local/data/repository/HdKeyAccountRepositoryImplTest.kt
  common-sdk/src/test/kotlin/com/algorand/wallet/account/local/data/repository/LedgerBleAccountRepositoryImplTest.kt
  common-sdk/src/test/kotlin/com/algorand/wallet/account/local/data/repository/NoAuthAccountRepositoryImplTest.kt
Labels: enhancement

#164 Pera 1689 :: Create new IsAccountRekeyedToAnotherAccountUseCase and replace isAccountRekeyed function with it
  app/src/main/kotlin/com/algorand/android/modules/accounts/di/AccountsModule.kt
  app/src/main/kotlin/com/algorand/android/modules/assetinbox/detail/receivedetail/domain/usecase/CreateArc59ClaimTransactionUseCase.kt
  app/src/main/kotlin/com/algorand/android/modules/assetinbox/detail/receivedetail/domain/usecase/CreateArc59RejectTransactionUseCase.kt
  app/src/main/kotlin/com/algorand/android/modules/assetinbox/send/domain/usecase/CreateArc59SendTransaction.kt
  app/src/main/kotlin/com/algorand/android/modules/assetinbox/send/domain/usecase/CreateArc59SendTransactionUseCase.kt
  app/src/main/kotlin/com/algorand/android/modules/assetinbox/send/domain/usecase/CreateArc59TransactionsUseCase.kt
  app/src/main/kotlin/com/algorand/android/modules/keyreg/domain/usecase/CreateKeyRegTransactionUseCase.kt
  app/src/main/kotlin/com/algorand/android/modules/swap/confirmswap/domain/usecase/CreateSwapQuoteTransactionsUseCase.kt
  app/src/main/kotlin/com/algorand/android/usecase/AccountDetailUseCase.kt
  common-sdk/src/main/kotlin/com/algorand/wallet/account/detail/di/AccountDetailModule.kt
  common-sdk/src/main/kotlin/com/algorand/wallet/account/detail/domain/usecase/AccountDetailUseCases.kt
  common-sdk/src/main/kotlin/com/algorand/wallet/account/detail/domain/usecase/IsAccountRekeyedToAnotherAccountUseCase.kt
  common-sdk/src/main/kotlin/com/algorand/wallet/account/info/di/AccountInformationModule.kt
  common-sdk/src/main/kotlin/com/algorand/wallet/account/info/domain/usecase/AccountInformationUseCases.kt
  common-sdk/src/test/kotlin/com/algorand/wallet/account/detail/domain/usecase/IsAccountRekeyedToAnotherAccountUseCaseTest.kt
Labels: epic

#159 PERA-1669 :: Replace isThereAnyAccountWithPublicKey fun with app module function
  app/src/main/kotlin/com/algorand/android/MainActivity.kt
  app/src/main/kotlin/com/algorand/android/MainViewModel.kt
  app/src/main/kotlin/com/algorand/android/core/AccountManager.kt
  app/src/main/kotlin/com/algorand/android/modules/onboarding/recoverypassphrase/enterpassphrase/ui/usecase/RecoverWithPassphrasePreviewUseCase.kt
  app/src/main/kotlin/com/algorand/android/modules/onboarding/registerwatchaccount/ui/usecase/WatchAccountRegistrationPreviewUseCase.kt
  app/src/main/kotlin/com/algorand/android/modules/rekey/rekeytoledgeraccount/confirmation/ui/RekeyToLedgerAccountConfirmationViewModel.kt
  app/src/main/kotlin/com/algorand/android/modules/rekey/rekeytoledgeraccount/confirmation/ui/usecase/RekeyToLedgerAccountConfirmationPreviewUseCase.kt
  app/src/main/kotlin/com/algorand/android/modules/transaction/detail/domain/usecase/InnerTransactionDetailPreviewUseCase.kt
  app/src/main/kotlin/com/algorand/android/modules/transaction/detail/domain/usecase/StandardTransactionDetailPreviewUseCase.kt
  app/src/main/kotlin/com/algorand/android/usecase/AccountDetailUseCase.kt
Labels: epic
