Repository perawallet/pera-android, pull requests merged in 2025-04, with the labels that each got.

#235 PERA-1897 :: Add in Cards Banner
  app/src/main/kotlin/com/algorand/android/banner/data/mapper/BannerTypeDecider.kt
  app/src/main/kotlin/com/algorand/android/banner/data/model/BannerTypeResponse.kt
  app/src/main/kotlin/com/algorand/android/banner/domain/mapper/BannerMapper.kt
  app/src/main/kotlin/com/algorand/android/banner/domain/model/BannerType.kt
  app/src/main/kotlin/com/algorand/android/banner/domain/model/BaseBanner.kt
  app/src/main/kotlin/com/algorand/android/banner/domain/usecase/BannersUseCase.kt
  app/src/main/kotlin/com/algorand/android/banner/ui/mapper/BaseBannerItemMapper.kt
  app/src/main/kotlin/com/algorand/android/banner/ui/viewholder/CardsBannerViewHolder.kt
  app/src/main/kotlin/com/algorand/android/modules/accounts/domain/model/BaseAccountListItem.kt
  app/src/main/kotlin/com/algorand/android/modules/accounts/domain/usecase/AccountsPreviewUseCase.kt
  app/src/main/kotlin/com/algorand/android/modules/accounts/ui/AccountsViewModel.kt
  app/src/main/kotlin/com/algorand/android/modules/accounts/ui/adapter/AccountAdapter.kt
  app/src/main/kotlin/com/algorand/android/modules/tracking/accounts/AccountsEventTracker.kt
  app/src/main/kotlin/com/algorand/android/modules/tracking/accounts/VisitGovernanceEventTracker.kt
  app/src/main/kotlin/com/algorand/android/modules/tracking/accounts/VisitStakingEventTracker.kt
  app/src/main/kotlin/com/algorand/android/modules/tracking/core/Constants.kt
  app/src/main/res/drawable-hdpi/bg_card_banner.png
  app/src/main/res/drawable-mdpi/bg_card_banner.png
  app/src/main/res/drawable-xhdpi/bg_card_banner.png
  app/src/main/res/drawable-xxhdpi/bg_card_banner.png
  app/src/main/res/drawable-xxxhdpi/bg_card_banner.png
  app/src/main/res/layout/item_card_banner.xml
  common-sdk/src/main/kotlin/com/algorand/wallet/account/custom/data/repository/CustomAccountInfoRepositoryImpl.kt
  common-sdk/src/main/kotlin/com/algorand/wallet/account/custom/data/repository/CustomHdSeedInfoRepositoryImpl.kt
  common-sdk/src/main/kotlin/com/algorand/wallet/account/custom/di/CustomInfoModule.kt
  common-sdk/src/main/kotlin/com/algorand/wallet/account/custom/domain/repository/CustomAccountInfoRepository.kt
  common-sdk/src/main/kotlin/com/algorand/wallet/account/custom/domain/repository/CustomHdSeedInfoRepository.kt
  common-sdk/src/main/kotlin/com/algorand/wallet/account/custom/domain/usecase/ClearAllCustomInformationUseCase.kt
  common-sdk/src/main/kotlin/com/algorand/wallet/account/custom/domain/usecase/CustomInfoUseCases.kt
  common-sdk/src/main/kotlin/com/algorand/wallet/account/local/di/LocalAccountsModule.kt
  common-sdk/src/main/kotlin/com/algorand/wallet/account/local/domain/usecase/DeleteAllLocalAccountsUseCase.kt
  common-sdk/src/main/kotlin/com/algorand/wallet/account/local/domain/usecase/LocalAccountUseCases.kt
  common-sdk/src/main/kotlin/com/algorand/wallet/algosdk/transaction/sdk/AlgoAccountSdkImpl.kt
  common-sdk/src/main/kotlin/com/algorand/wallet/asset/data/database/dao/CollectibleDao.kt
  common-sdk/src/main/kotlin/com/algorand/wallet/asset/data/repository/AssetDetailCacheHelper.kt
  common-sdk/src/main/kotlin/com/algorand/wallet/asset/data/repository/AssetDetailCacheHelperImpl.kt
  common-sdk/src/main/kotlin/com/algorand/wallet/asset/data/repository/AssetRepositoryImpl.kt
  common-sdk/src/main/kotlin/com/algorand/wallet/asset/di/AssetDetailUseCaseModule.kt
  common-sdk/src/main/kotlin/com/algorand/wallet/asset/domain/repository/AssetRepository.kt
  common-sdk/src/main/kotlin/com/algorand/wallet/asset/domain/usecase/AssetUseCases.kt
  common-sdk/src/test/kotlin/com/algorand/wallet/account/custom/domain/usecase/ClearAllCustomInformationUseCaseTest.kt
  common-sdk/src/test/kotlin/com/algorand/wallet/account/local/domain/usecase/DeleteAllLocalAccountsUseCaseTest.kt
  gradle/libs.versions.toml
Labels: enhancement

#237 PERA-1828 :: Add tracking for recover account type click
  app/src/main/kotlin/com/algorand/android/modules/onboarding/recoverypassphrase/info/ui/RecoverAccountInfoFragment.kt
  app/src/main/kotlin/com/algorand/android/modules/onboarding/recoverypassphrase/info/ui/RecoveryAccountInfoViewModel.kt
  app/src/main/kotlin/com/algorand/android/modules/tracking/core/TrackingConstants.kt
Labels: enhancement

#238 PERA-1717 :: Fix asset inbox signing for HD accounts
  app/src/main/kotlin/com/algorand/android/core/transaction/external/ExternalTransactionSignManager.kt
  app/src/main/kotlin/com/algorand/android/modules/assetinbox/detail/receivedetail/ui/Arc59ClaimRejectTransactionSignManager.kt
  app/src/main/kotlin/com/algorand/android/modules/assetinbox/send/summary/ui/Arc59SendTransactionSignManager.kt
  app/src/main/kotlin/com/algorand/android/modules/keyreg/domain/KeyRegTransactionSignManager.kt
  app/src/main/kotlin/com/algorand/android/modules/swap/confirmswap/domain/SwapTransactionSignManager.kt
  app/src/main/kotlin/com/algorand/android/utils/walletconnect/WalletConnectArbitraryDataSignManager.kt
  app/src/main/kotlin/com/algorand/android/utils/walletconnect/WalletConnectTransactionSignManager.kt
Labels: enhancement

#242 PERA-1284 :: Refactor account fast lookup implementation
  app/src/main/kotlin/com/algorand/android/dependencyinjection/NetworkModule.kt
  app/src/main/kotlin/com/algorand/android/ui/onboarding/reccoverypassphrase/importregisteredaddresses/RecoverRegisteredAccountsFragment.kt
  app/src/main/kotlin/com/algorand/android/ui/onboarding/reccoverypassphrase/importregisteredaddresses/RecoverRegisteredAccountsViewModel.kt
  common-sdk/src/main/kotlin/com/algorand/wallet/account/info/di/AccountInformationModule.kt
  common-sdk/src/main/kotlin/com/algorand/wallet/account/info/domain/model/RegisteredHdKey.kt
  common-sdk/src/main/kotlin/com/algorand/wallet/account/info/domain/usecase/AccountInformationUseCases.kt
  common-sdk/src/main/kotlin/com/algorand/wallet/account/info/domain/usecase/GetRegisteredHdKeysUseCase.kt
  common-sdk/src/main/kotlin/com/algorand/wallet/algosdk/domain/model/RegisteredAlgorandAccount.kt
  common-sdk/src/main/kotlin/com/algorand/wallet/algosdk/transaction/sdk/PeraBip39Sdk.kt
  common-sdk/src/main/kotlin/com/algorand/wallet/algosdk/transaction/sdk/PeraBip39SdkImpl.kt
  common-sdk/src/test/kotlin/com/algorand/wallet/account/info/domain/usecase/GetRegisteredHdKeysUseCaseTest.kt
Labels: enhancement

#241 PERA-1284 :: Add HD recovery scanning screen related code
  app/src/main/kotlin/com/algorand/android/dependencyinjection/NetworkModule.kt
  app/src/main/kotlin/com/algorand/android/modules/accountcore/ui/usecase/GetAccountOriginalStateIconDrawablePreviewUseCase.kt
  app/src/main/kotlin/com/algorand/android/modules/accountdetail/accountstatusdetail/ui/decider/AccountStatusDetailPreviewDecider.kt
  app/src/main/kotlin/com/algorand/android/modules/accounts/domain/usecase/AccountDetailSummaryUseCase.kt
  app/src/main/kotlin/com/algorand/android/modules/accounts/ui/AccountPreviewProcessor.kt
  app/src/main/kotlin/com/algorand/android/modules/onboarding/recoverypassphrase/enterpassphrase/ui/RecoverWithPassphraseFragment.kt
  app/src/main/kotlin/com/algorand/android/modules/onboarding/recoverypassphrase/enterpassphrase/ui/RecoverWithPassphraseViewModel.kt
  app/src/main/kotlin/com/algorand/android/modules/onboarding/recoverypassphrase/enterpassphrase/ui/usecase/RecoverWithPassphrasePreviewUseCase.kt
  app/src/main/kotlin/com/algorand/android/modules/onboarding/recoverypassphrase/result/ui/RecoverAccountResultInfoViewModel.kt
  app/src/main/kotlin/com/algorand/android/ui/accounts/ViewPassphraseLockViewModel.kt
  app/src/main/kotlin/com/algorand/android/ui/compose/theme/PeraColor.kt
  app/src/main/kotlin/com/algorand/android/ui/compose/widget/PeraButton.kt
  app/src/main/kotlin/com/algorand/android/ui/compose/widget/PeraCard.kt
  app/src/main/kotlin/com/algorand/android/ui/compose/widget/PeraCheckbox.kt
  app/src/main/kotlin/com/algorand/android/ui/compose/widget/PeraText.kt
  app/src/main/kotlin/com/algorand/android/ui/onboarding/reccoverypassphrase/importregisteredaddresses/RecoverRegisteredAccountsFragment.kt
  app/src/main/kotlin/com/algorand/android/ui/onboarding/reccoverypassphrase/importregisteredaddresses/RecoverRegisteredAccountsViewModel.kt
  app/src/main/kotlin/com/algorand/android/ui/register/nameregistration/NameRegistrationViewModel.kt
  app/src/main/res/navigation/recover_with_passphrase_navigation.xml
  app/src/main/res/values/strings.xml
  common-sdk/src/main/kotlin/com/algorand/wallet/account/info/di/AccountInformationModule.kt
  common-sdk/src/main/kotlin/com/algorand/wallet/account/info/domain/model/RegisteredHdKey.kt
  common-sdk/src/main/kotlin/com/algorand/wallet/account/info/domain/usecase/AccountInformationUseCases.kt
  common-sdk/src/main/kotlin/com/algorand/wallet/account/info/domain/usecase/GetRegisteredHdKeysUseCase.kt
  common-sdk/src/main/kotlin/com/algorand/wallet/algosdk/transaction/sdk/PeraBip39Sdk.kt
  common-sdk/src/main/kotlin/com/algorand/wallet/algosdk/transaction/sdk/PeraBip39SdkImpl.kt
  common-sdk/src/test/kotlin/com/algorand/wallet/account/info/domain/usecase/GetRegisteredHdKeysUseCaseTest.kt
Labels: enhancement

#243 PERA-1924 :: Add icon for hd accounts
  app/src/main/kotlin/com/algorand/android/models/AccountIconResource.kt
  app/src/main/kotlin/com/algorand/android/modules/accountcore/ui/usecase/GetAccountIconDrawablePreviewUseCase.kt
  app/src/main/kotlin/com/algorand/android/modules/accountcore/ui/usecase/GetAccountOriginalStateIconDrawablePreviewUseCase.kt
  app/src/main/kotlin/com/algorand/android/modules/asb/importbackup/accountselection/ui/usecase/AsbImportAccountSelectionPreviewUseCase.kt
  app/src/main/res/drawable/ic_hd_wallet.xml
Labels: enhancement

#194 PERA-1766 :: remove add pin step in onboarding flow
  app/src/main/kotlin/com/algorand/android/modules/onboarding/recoverypassphrase/nameregistration/RecoverAccountNameRegistrationFragment.kt
  app/src/main/kotlin/com/algorand/android/ui/register/createaccount/name/CreateAccountNameRegistrationFragment.kt
  app/src/main/res/navigation/backup_passphrase_account_name_navigation.xml
  app/src/main/res/navigation/home_navigation.xml
  app/src/main/res/navigation/recover_with_passphrase_navigation.xml
Labels: enhancement

#236 PERA-1800 :: Set accountCreation to be null during backup process
  app/src/main/kotlin/com/algorand/android/modules/accounts/ui/AccountPreviewProcessor.kt
  app/src/main/kotlin/com/algorand/android/ui/common/warningconfirmation/BackupInfoFragment.kt
  app/src/main/kotlin/com/algorand/android/ui/common/warningconfirmation/WriteDownInfoFragment.kt
  app/src/main/kotlin/com/algorand/android/ui/register/BackupPassphraseViewModel.kt
  app/src/main/kotlin/com/algorand/android/ui/register/PassphraseValidationFragment.kt
  app/src/main/kotlin/com/algorand/android/ui/register/PassphraseValidationViewModel.kt
  app/src/main/res/navigation/backup_passphrase_info_navigation.xml
  app/src/main/res/navigation/backup_passphrase_navigation.xml
Labels: bug

#244 PERA-1928 :: Migrate navigation initialization
  app/src/main/kotlin/com/algorand/android/CoreMainActivity.kt
  app/src/main/kotlin/com/algorand/android/CoreMainViewModel.kt
  app/src/main/kotlin/com/algorand/android/core/LegacyAccountManager.kt
  app/src/main/kotlin/com/algorand/android/core/PeraApp.kt
  app/src/main/kotlin/com/algorand/android/dependencyinjection/AppModule.kt
  app/src/main/kotlin/com/algorand/android/usecase/DeleteAllDataUseCase.kt
Labels: bug

#245 PERA-1939 :: AccountStatusDetail conversion to event/state structure
  app/src/main/kotlin/com/algorand/android/mapper/AccountSummaryMapper.kt
  app/src/main/kotlin/com/algorand/android/models/AccountDetailSummary.kt
  app/src/main/kotlin/com/algorand/android/modules/accountdetail/accountstatusdetail/ui/AccountStatusDetailBottomSheet.kt
  app/src/main/kotlin/com/algorand/android/modules/accountdetail/accountstatusdetail/ui/AccountStatusDetailViewModel.kt
  app/src/main/kotlin/com/algorand/android/modules/accountdetail/accountstatusdetail/ui/decider/AccountStatusDetailPreviewDecider.kt
  app/src/main/kotlin/com/algorand/android/modules/accountdetail/accountstatusdetail/ui/mapper/AccountStatusDetailPreviewMapper.kt
  app/src/main/kotlin/com/algorand/android/modules/accountdetail/accountstatusdetail/ui/usecase/AccountStatusDetailPreviewUseCase.kt
  app/src/main/kotlin/com/algorand/android/modules/accounts/domain/usecase/AccountDetailSummaryUseCase.kt
  app/src/main/kotlin/com/algorand/android/modules/onboarding/pairledger/instruction/ui/LedgerInstructionFragment.kt
  app/src/main/kotlin/com/algorand/android/modules/onboarding/recoverypassphrase/enterpassphrase/ui/RecoverWithPassphraseFragment.kt
  app/src/main/kotlin/com/algorand/android/modules/onboarding/recoverypassphrase/info/ui/RecoverAccountInfoFragment.kt
  app/src/main/kotlin/com/algorand/android/modules/onboarding/recoverypassphrase/options/ui/RecoverOptionsBottomSheet.kt
  app/src/main/kotlin/com/algorand/android/ui/onboarding/recoverypassphrase/importregisteredaddresses/RecoverRegisteredAccountsFragment.kt
  app/src/main/kotlin/com/algorand/android/ui/onboarding/recoverypassphrase/importregisteredaddresses/RecoverRegisteredAccountsScreen.kt
  app/src/main/kotlin/com/algorand/android/ui/onboarding/recoverypassphrase/importregisteredaddresses/RecoverRegisteredAccountsViewModel.kt
  app/src/main/kotlin/com/algorand/android/utils/browser/BrowserUtils.kt
  app/src/main/res/navigation/recover_with_passphrase_navigation.xml
  app/src/main/res/values/strings.xml
Labels: enhancement

#248 PERA-1965 :: Fix bug for passphrase validation next button
  app/src/main/kotlin/com/algorand/android/ui/register/PassphraseValidationFragment.kt
Labels: bug

#255 PERA-1995 :: Universal Wallet copy change
  app/src/main/kotlin/com/algorand/android/modules/accountdetail/accountstatusdetail/ui/decider/AccountStatusDetailPreviewDecider.kt
  app/src/main/kotlin/com/algorand/android/modules/onboarding/recoverypassphrase/info/ui/RecoverAccountInfoFragment.kt
  app/src/main/kotlin/com/algorand/android/ui/register/registerintro/RegisterIntroFragment.kt
  app/src/main/res/values/strings.xml
Labels: enhancement

#262 PERA-2024 :: Hide exchange fee in app UI
  app/src/main/kotlin/com/algorand/android/modules/swap/transactionsummary/ui/adapter/SwapFeesItemViewHolder.kt
  app/src/main/res/layout/bottom_sheet_swap_preview_summary.xml
  app/src/main/res/layout/fragment_confirm_swap.xml
Labels: enhancement

#256 PERA-1957 :: Fix copy on rekey screens
  app/src/main/kotlin/com/algorand/android/modules/rekey/rekeytoledgeraccount/instruction/ui/decider/RekeyToLedgerAccountPreviewDecider.kt
  app/src/main/kotlin/com/algorand/android/modules/rekey/rekeytostandardaccount/instruction/ui/decider/RekeyToStandardAccountIntroductionPreviewDecider.kt
  app/src/main/res/drawable-hdpi/ic_rekey_from_algo25_banner.jpg
  app/src/main/res/drawable-hdpi/ic_rekey_from_hdkey_banner.jpg
  app/src/main/res/drawable-mdpi/ic_rekey_from_algo25_banner.jpg
  app/src/main/res/drawable-mdpi/ic_rekey_from_hdkey_banner.jpg
  app/src/main/res/drawable-xhdpi/ic_rekey_from_algo25_banner.jpg
  app/src/main/res/drawable-xhdpi/ic_rekey_from_hdkey_banner.jpg
  app/src/main/res/drawable-xxhdpi/ic_rekey_from_algo25_banner.jpg
  app/src/main/res/drawable-xxhdpi/ic_rekey_from_hdkey_banner.jpg
  app/src/main/res/drawable-xxxhdpi/ic_rekey_from_algo25_banner.jpg
  app/src/main/res/drawable-xxxhdpi/ic_rekey_from_hdkey_banner.jpg
  gradle/libs.versions.toml
Labels: bug

#266 PERA-2078 :: Add hd design spec and flows
  .github/workflows/cla.yml
  LICENSE.txt
  hd_kms_spec.md
Labels: documentation

#270 PERA-1962 :: Fix arbitrary data signing for hd key accounts
  app/src/main/kotlin/com/algorand/android/models/WalletConnectArbitraryDataSigner.kt
  app/src/main/kotlin/com/algorand/android/modules/walletconnect/domain/usecase/GetWalletConnectTransactionSignerUseCase.kt
  app/src/main/kotlin/com/algorand/android/ui/wcarbitrarydatarequest/WalletConnectArbitraryDataRequestViewModel.kt
  app/src/main/kotlin/com/algorand/android/utils/walletconnect/WalletConnectArbitraryDataSignManager.kt
Labels: bug

#272 PERA-1962 :: Fix test in GetWalletConnectTransactionSignerUseCaseTest
  app/src/test/kotlin/com/algorand/android/modules/walletconnect/domain/usecase/GetWalletConnectTransactionSignerUseCaseTest.kt
Labels: bug
