Repository perawallet/pera-android, pull requests merged in 2025-03, with the labels that each got.

#170 PERA-1705 :: Collectible Detail - Dev - Common Sdk Sync
  common-sdk/src/main/kotlin/com/algorand/wallet/account/info/domain/usecase/AccountInformationUseCases.kt
  common-sdk/src/main/kotlin/com/algorand/wallet/account/info/domain/usecase/IsAssetOwnedByAccountUseCase.kt
  common-sdk/src/main/kotlin/com/algorand/wallet/asset/data/database/model/CollectibleMediaEntity.kt
  common-sdk/src/main/kotlin/com/algorand/wallet/asset/data/database/model/CollectibleMediaTypeExtensionEntity.kt
  common-sdk/src/main/kotlin/com/algorand/wallet/asset/data/mapper/entity/CollectibleMediaEntityMapperImpl.kt
  common-sdk/src/main/kotlin/com/algorand/wallet/asset/data/mapper/entity/CollectibleMediaTypeExtensionEntityMapper.kt
  common-sdk/src/main/kotlin/com/algorand/wallet/asset/data/mapper/entity/CollectibleMediaTypeExtensionEntityMapperImpl.kt
  common-sdk/src/main/kotlin/com/algorand/wallet/asset/data/mapper/model/AssetInfoMapperImpl.kt
  common-sdk/src/main/kotlin/com/algorand/wallet/asset/data/mapper/model/collectible/AudioCollectibleDetailMapperImpl.kt
  common-sdk/src/main/kotlin/com/algorand/wallet/asset/data/mapper/model/collectible/CollectibleMediaMapperImpl.kt
  common-sdk/src/main/kotlin/com/algorand/wallet/asset/data/mapper/model/collectible/CollectibleMediaTypeExtensionMapper.kt
  common-sdk/src/main/kotlin/com/algorand/wallet/asset/data/mapper/model/collectible/CollectibleMediaTypeExtensionMapperImpl.kt
  common-sdk/src/main/kotlin/com/algorand/wallet/asset/data/mapper/model/collectible/ImageCollectibleDetailMapperImpl.kt
  common-sdk/src/main/kotlin/com/algorand/wallet/asset/data/mapper/model/collectible/MixedCollectibleDetailMapperImpl.kt
  common-sdk/src/main/kotlin/com/algorand/wallet/asset/data/mapper/model/collectible/UnsupportedCollectibleDetailMapperImpl.kt
  common-sdk/src/main/kotlin/com/algorand/wallet/asset/data/mapper/model/collectible/VideoCollectibleDetailMapperImpl.kt
  common-sdk/src/main/kotlin/com/algorand/wallet/asset/data/model/NodeAssetDetailParamsResponse.kt
  common-sdk/src/main/kotlin/com/algorand/wallet/asset/data/model/collectible/CollectibleMediaResponse.kt
  common-sdk/src/main/kotlin/com/algorand/wallet/asset/data/model/collectible/CollectibleMediaTypeExtensionResponse.kt
  common-sdk/src/main/kotlin/com/algorand/wallet/asset/di/AssetDetailMappersModule.kt
  common-sdk/src/main/kotlin/com/algorand/wallet/asset/di/AssetDetailUseCaseModule.kt
  common-sdk/src/main/kotlin/com/algorand/wallet/asset/domain/model/Asset.kt
  common-sdk/src/main/kotlin/com/algorand/wallet/asset/domain/model/BaseCollectibleMedia.kt
  common-sdk/src/main/kotlin/com/algorand/wallet/asset/domain/model/CollectibleDetail.kt
  common-sdk/src/main/kotlin/com/algorand/wallet/asset/domain/model/CollectibleMedia.kt
  common-sdk/src/main/kotlin/com/algorand/wallet/asset/domain/model/CollectibleMediaTypeExtension.kt
  common-sdk/src/main/kotlin/com/algorand/wallet/asset/domain/usecase/AssetUseCases.kt
  common-sdk/src/main/kotlin/com/algorand/wallet/asset/domain/usecase/InitializeAssetsUseCase.kt
  common-sdk/src/main/kotlin/com/algorand/wallet/asset/domain/util/AssetConstants.kt
  common-sdk/src/main/kotlin/com/algorand/wallet/foundation/database/PeraDatabase.kt
  common-sdk/src/main/kotlin/com/algorand/wallet/foundation/database/converters/CollectibleMediaTypeExtensionTypeConverter.kt
  common-sdk/src/test/kotlin/com/algorand/wallet/account/info/domain/usecase/IsAssetOwnedByAccountUseCaseTest.kt
  common-sdk/src/test/kotlin/com/algorand/wallet/asset/data/mapper/entity/CollectibleMediaEntityMapperImplTest.kt
  common-sdk/src/test/kotlin/com/algorand/wallet/asset/data/mapper/entity/CollectibleMediaTypeExtensionEntityMapperImplTest.kt
  common-sdk/src/test/kotlin/com/algorand/wallet/asset/data/mapper/model/collectible/CollectibleMapperImplTest.kt
  common-sdk/src/test/kotlin/com/algorand/wallet/asset/data/mapper/model/collectible/CollectibleMediaMapperImplTest.kt
  common-sdk/src/test/kotlin/com/algorand/wallet/asset/data/mapper/model/collectible/CollectibleMediaTypeExtensionMapperImplTest.kt
  common-sdk/src/test/kotlin/com/algorand/wallet/asset/domain/InitializeAssetsUseCaseTest.kt
Labels: enhancement

#172 PERA-1709 :: ReferralRepository refactor - dev branch update
  app/src/main/kotlin/com/algorand/android/cache/PersistentCacheProviderImpl.kt
  app/src/main/kotlin/com/algorand/android/cache/SharedPrefPersistentCache.kt
  app/src/main/kotlin/com/algorand/android/cache/di/AppCacheModule.kt
  common-sdk/src/main/kotlin/com/algorand/wallet/analytics/data/repository/ReferrerRepositoryImpl.kt
  common-sdk/src/main/kotlin/com/algorand/wallet/analytics/di/AnalyticsModule.kt
  common-sdk/src/main/kotlin/com/algorand/wallet/foundation/cache/PersistentCache.kt
  common-sdk/src/main/kotlin/com/algorand/wallet/foundation/cache/PersistentCacheProvider.kt
  common-sdk/src/test/kotlin/com/algorand/wallet/analytics/data/service/PeraEventTrackerImplTest.kt
  common-sdk/src/test/kotlin/com/algorand/wallet/analytics/repository/ReferrerRepositoryImplTest.kt
Labels: enhancement

#168 PERA-1621 :: Add requested missing analytics events
  app/src/main/kotlin/com/algorand/android/MainActivity.kt
  app/src/main/kotlin/com/algorand/android/MainViewModel.kt
  app/src/main/kotlin/com/algorand/android/core/BaseViewModel.kt
  app/src/main/kotlin/com/algorand/android/core/PeraApp.kt
  app/src/main/kotlin/com/algorand/android/modules/accountdetail/ui/AccountDetailFragment.kt
  app/src/main/kotlin/com/algorand/android/modules/accountdetail/ui/AccountDetailViewModel.kt
  app/src/main/kotlin/com/algorand/android/modules/accounts/ui/AccountsFragment.kt
  app/src/main/kotlin/com/algorand/android/modules/accounts/ui/AccountsViewModel.kt
  app/src/main/kotlin/com/algorand/android/modules/onboarding/registerwatchaccount/ui/RegisterWatchAccountFragment.kt
  app/src/main/kotlin/com/algorand/android/modules/onramp/ui/BuySellActionsBottomSheet.kt
  app/src/main/kotlin/com/algorand/android/modules/onramp/ui/BuySellActionsBottomSheetViewModel.kt
  app/src/main/kotlin/com/algorand/android/modules/swap/assetswap/ui/AssetSwapViewModel.kt
  app/src/main/kotlin/com/algorand/android/modules/tracking/accounts/AccountsEventTracker.kt
  app/src/main/kotlin/com/algorand/android/modules/tracking/accounts/AccountsQrConnectEventTracker.kt
  app/src/main/kotlin/com/algorand/android/modules/tracking/accounts/AccountsQrScanEventTracker.kt
  app/src/main/kotlin/com/algorand/android/modules/tracking/bottomnavigation/BottomNavigationAccountsTapEventTracker.kt
  app/src/main/kotlin/com/algorand/android/modules/tracking/bottomnavigation/BottomNavigationAlgoBuyTapEventTracker.kt
  app/src/main/kotlin/com/algorand/android/modules/tracking/bottomnavigation/BottomNavigationEventTracker.kt
  app/src/main/kotlin/com/algorand/android/modules/tracking/core/Constants.kt
  app/src/main/kotlin/com/algorand/android/modules/tracking/main/MainActivityEventTracker.kt
  app/src/main/kotlin/com/algorand/android/modules/tracking/onboarding/register/registerintro/OnboardingCreateWatchAccountEventTracker.kt
  app/src/main/kotlin/com/algorand/android/modules/tracking/onboarding/register/registerintro/OnboardingWelcomeAccountSkipEventTracker.kt
  app/src/main/kotlin/com/algorand/android/modules/tracking/onboarding/register/registerintro/RegisterIntroFragmentEventTracker.kt
  app/src/main/kotlin/com/algorand/android/modules/tracking/swap/quickaction/QuickActionSwapButtonClickEventTracker.kt
  app/src/main/kotlin/com/algorand/android/ui/accounts/AccountsQrScannerFragment.kt
  app/src/main/kotlin/com/algorand/android/ui/accounts/AccountsQrScannerViewModel.kt
  app/src/main/kotlin/com/algorand/android/ui/common/warningconfirmation/BackupInfoFragment.kt
  app/src/main/kotlin/com/algorand/android/ui/common/warningconfirmation/WriteDownInfoFragment.kt
  app/src/main/kotlin/com/algorand/android/ui/register/BackupPassphraseFragment.kt
  app/src/main/kotlin/com/algorand/android/ui/register/PassphraseValidationFragment.kt
  app/src/main/kotlin/com/algorand/android/ui/register/createaccount/name/CreateAccountNameRegistrationFragment.kt
  app/src/main/kotlin/com/algorand/android/ui/register/nameregistration/BaseNameRegistrationFragment.kt
  app/src/main/kotlin/com/algorand/android/ui/register/nameregistration/NameRegistrationViewModel.kt
  app/src/main/kotlin/com/algorand/android/ui/register/registerintro/RegisterIntroFragment.kt
  app/src/main/kotlin/com/algorand/android/ui/register/registerintro/RegisterIntroViewModel.kt
  app/src/main/kotlin/com/algorand/android/usecase/RegisterIntroPreviewUseCase.kt
  app/src/main/kotlin/com/algorand/android/utils/analytics/AssetDetailEventUtils.kt
  app/src/main/kotlin/com/algorand/android/utils/analytics/ReceiveEventUtils.kt
  app/src/main/kotlin/com/algorand/android/utils/analytics/SendEventUtils.kt
Labels: enhancement

#174 PERA-1714 :: Refactor remove account warning bottom sheet
  app/src/main/kotlin/com/algorand/android/modules/accountdetail/removeaccount/ui/RemoveAccountConfirmationBottomSheet.kt
  app/src/main/kotlin/com/algorand/android/modules/accountdetail/removeaccount/ui/RemoveAccountConfirmationViewModel.kt
  app/src/main/kotlin/com/algorand/android/modules/accountdetail/removeaccount/ui/mapper/RemoveAccountConfirmationPreviewMapper.kt
  app/src/main/kotlin/com/algorand/android/modules/accountdetail/removeaccount/ui/model/RemoveAccountConfirmationPreview.kt
  app/src/main/kotlin/com/algorand/android/modules/accountdetail/removeaccount/ui/usecase/RemoveAccountConfirmationPreviewUseCase.kt
  app/src/main/kotlin/com/algorand/android/usecase/AccountDetailUseCase.kt
  app/src/main/kotlin/com/algorand/android/utils/BaseDoubleButtonBottomSheet.kt
  common-sdk/test-coverage/coverageValidator.sh
Labels: epic

#177 PERA-1716 :: Refactor rekey and undo rekey flows
  app/src/main/kotlin/com/algorand/android/modules/accounticon/ui/usecase/CreateAccountOriginalStateIconDrawableUseCase.kt
  app/src/main/kotlin/com/algorand/android/modules/basemultipleaccountselection/ui/usecase/BaseMultipleAccountSelectionPreviewUseCase.kt
  app/src/main/kotlin/com/algorand/android/modules/rekey/baserekeyconfirmation/ui/BaseRekeyConfirmationFragment.kt
  app/src/main/kotlin/com/algorand/android/modules/rekey/baserekeyconfirmation/ui/model/BaseRekeyConfirmationFields.kt
  app/src/main/kotlin/com/algorand/android/modules/rekey/rekeytoledgeraccount/confirmation/ui/mapper/RekeyToLedgerAccountConfirmationPreviewMapper.kt
  app/src/main/kotlin/com/algorand/android/modules/rekey/rekeytoledgeraccount/confirmation/ui/model/RekeyToLedgerAccountConfirmationPreview.kt
  app/src/main/kotlin/com/algorand/android/modules/rekey/rekeytoledgeraccount/confirmation/ui/usecase/RekeyToLedgerAccountConfirmationPreviewUseCase.kt
  app/src/main/kotlin/com/algorand/android/modules/rekey/rekeytostandardaccount/confirmation/ui/mapper/RekeyToStandardAccountConfirmationPreviewMapper.kt
  app/src/main/kotlin/com/algorand/android/modules/rekey/rekeytostandardaccount/confirmation/ui/model/RekeyToStandardAccountConfirmationPreview.kt
  app/src/main/kotlin/com/algorand/android/modules/rekey/rekeytostandardaccount/confirmation/ui/usecase/RekeyToStandardAccountConfirmationPreviewUseCase.kt
  app/src/main/kotlin/com/algorand/android/modules/rekey/undorekey/confirmation/ui/UndoRekeyConfirmationFragment.kt
  app/src/main/kotlin/com/algorand/android/modules/rekey/undorekey/confirmation/ui/UndoRekeyConfirmationViewModel.kt
  app/src/main/kotlin/com/algorand/android/modules/rekey/undorekey/confirmation/ui/mapper/UndoRekeyConfirmationPreviewMapper.kt
  app/src/main/kotlin/com/algorand/android/modules/rekey/undorekey/confirmation/ui/model/UndoRekeyConfirmationPreview.kt
  app/src/main/kotlin/com/algorand/android/modules/rekey/undorekey/confirmation/ui/usecase/UndoRekeyConfirmationPreviewUseCase.kt
  app/src/main/kotlin/com/algorand/android/modules/rekey/undorekey/previousrekeyundoneconfirmation/ui/PreviousRekeyUndoneConfirmationBottomSheet.kt
  app/src/main/kotlin/com/algorand/android/modules/rekey/undorekey/previousrekeyundoneconfirmation/ui/PreviousRekeyUndoneConfirmationViewModel.kt
  app/src/main/kotlin/com/algorand/android/modules/rekey/undorekey/resultinfo/ui/UndoRekeyVerifyInfoFragment.kt
  app/src/main/kotlin/com/algorand/android/modules/rekey/undorekey/resultinfo/ui/UndoRekeyVerifyInfoViewModel.kt
  app/src/main/kotlin/com/algorand/android/modules/rekey/undorekey/resultinfo/ui/model/PreviousRekeyUndoneConfirmationPreview.kt
  app/src/main/kotlin/com/algorand/android/modules/rekey/undorekey/resultinfo/ui/usecase/UndoRekeyVerifyInfoPreviewUseCase.kt
  app/src/main/kotlin/com/algorand/android/utils/BaseDoubleButtonBottomSheet.kt
  app/src/main/res/navigation/rekey_undo_navigation.xml
Labels: epic

#183 PERA-1738 :: Remove multiple functions from AccountDetailUseCase
  app/src/main/kotlin/com/algorand/android/MainActivity.kt
  app/src/main/kotlin/com/algorand/android/MainViewModel.kt
  app/src/main/kotlin/com/algorand/android/modules/assets/action/trylater/UnsupportedAddAssetTryLaterBottomSheet.kt
  app/src/main/kotlin/com/algorand/android/modules/deeplink/ui/DeeplinkHandler.kt
  app/src/main/kotlin/com/algorand/android/modules/qrscanning/QrScannerViewModel.kt
  app/src/main/kotlin/com/algorand/android/modules/webimport/loading/ui/WebImportLoadingViewModel.kt
  app/src/main/kotlin/com/algorand/android/modules/webimport/loading/ui/usecase/WebImportLoadingPreviewUseCase.kt
  app/src/main/kotlin/com/algorand/android/usecase/AccountDetailUseCase.kt
  app/src/main/kotlin/com/algorand/android/usecase/AccountInformationUseCase.kt
  app/src/main/kotlin/com/algorand/android/utils/coremanager/LocalAccountsNameServiceManager.kt
  common-sdk/src/main/kotlin/com/algorand/wallet/account/info/data/database/dao/AssetHoldingDao.kt
  common-sdk/src/main/kotlin/com/algorand/wallet/account/info/data/repository/AccountInformationRepositoryImpl.kt
  common-sdk/src/main/kotlin/com/algorand/wallet/account/info/di/AccountInformationModule.kt
  common-sdk/src/main/kotlin/com/algorand/wallet/account/info/domain/repository/AccountInformationRepository.kt
  common-sdk/src/main/kotlin/com/algorand/wallet/account/info/domain/usecase/AccountInformationUseCases.kt
  common-sdk/src/test/kotlin/com/algorand/wallet/account/info/data/repository/AccountInformationRepositoryImplTest.kt
Labels: epic

#186 PERA-1750 :: Refactor AccountQuickActionsFragment
  app/src/main/kotlin/com/algorand/android/MainViewModel.kt
  app/src/main/kotlin/com/algorand/android/modules/accountdetail/quickaction/genericaccount/AccountQuickActionsViewModel.kt
  app/src/main/kotlin/com/algorand/android/modules/accountdetail/quickaction/genericaccount/ui/usecase/AccountQuickActionsPreviewUseCase.kt
Labels: epic

#187 PERA-1752 :: Add pushDappViewerScreen event handling to DiscoverDetail Screen
  app/src/main/kotlin/com/algorand/android/discover/detail/ui/DiscoverDetailFragment.kt
  app/src/main/kotlin/com/algorand/android/discover/detail/ui/DiscoverDetailViewModel.kt
  app/src/main/kotlin/com/algorand/android/discover/detail/ui/model/DiscoverDetailPreview.kt
  app/src/main/kotlin/com/algorand/android/discover/detail/ui/usecase/DiscoverDetailPreviewUseCase.kt
  app/src/main/res/navigation/discover_detail_navigation.xml
Labels: bug

#188 PERA-1754 :: Remove some functions from AccountDetailUseCase
  app/src/main/kotlin/com/algorand/android/mapper/AccountAssetDataMapper.kt
  app/src/main/kotlin/com/algorand/android/mapper/AccountBalanceMapper.kt
  app/src/main/kotlin/com/algorand/android/models/AccountBalance.kt
  app/src/main/kotlin/com/algorand/android/modules/accountcore/di/AccountCoreUiModule.kt
  app/src/main/kotlin/com/algorand/android/modules/accountcore/domain/usecase/AccountCoreUseCases.kt
  app/src/main/kotlin/com/algorand/android/modules/accountcore/domain/usecase/GetAccountTotalValueFlowUseCase.kt
  app/src/main/kotlin/com/algorand/android/modules/accountcore/domain/usecase/GetAccountTotalValueUseCase.kt
  app/src/main/kotlin/com/algorand/android/modules/accountdetail/history/ui/AccountHistoryViewModel.kt
  app/src/main/kotlin/com/algorand/android/modules/accounts/domain/mapper/AccountValueMapper.kt
  app/src/main/kotlin/com/algorand/android/modules/accounts/domain/model/AccountValue.kt
  app/src/main/kotlin/com/algorand/android/modules/accounts/domain/usecase/GetAccountValueUseCase.kt
  app/src/main/kotlin/com/algorand/android/modules/assetinbox/detail/receivedetail/ui/mapper/Arc59ReceiveDetailPreviewMapperImpl.kt
  app/src/main/kotlin/com/algorand/android/modules/dapp/bidali/ui/browser/BidaliBrowserViewModel.kt
  app/src/main/kotlin/com/algorand/android/modules/dapp/bidali/ui/browser/usecase/BidaliBrowserPreviewUseCase.kt
  app/src/main/kotlin/com/algorand/android/modules/onboarding/recoverypassphrase/enterpassphrase/ui/usecase/RecoverWithPassphrasePreviewUseCase.kt
  app/src/main/kotlin/com/algorand/android/modules/perawebview/GetAuthorizedAddressesWebMessagesUseCase.kt
  app/src/main/kotlin/com/algorand/android/modules/webimport/loading/ui/usecase/WebImportLoadingPreviewUseCase.kt
  app/src/main/kotlin/com/algorand/android/repository/AccountRepository.kt
  app/src/main/kotlin/com/algorand/android/usecase/AccountAlgoAmountUseCase.kt
  app/src/main/kotlin/com/algorand/android/usecase/AccountAssetAmountUseCase.kt
  app/src/main/kotlin/com/algorand/android/usecase/AccountAssetDataUseCase.kt
  app/src/main/kotlin/com/algorand/android/usecase/AccountDetailUseCase.kt
  app/src/main/kotlin/com/algorand/android/usecase/AccountHistoryUseCase.kt
  app/src/main/kotlin/com/algorand/android/usecase/AccountTotalBalanceUseCase.kt
  app/src/main/kotlin/com/algorand/android/usecase/AssetDetailUseCase.kt
  app/src/main/kotlin/com/algorand/android/usecase/GetAccountTotalAssetValueUseCase.kt
  app/src/main/kotlin/com/algorand/android/usecase/GetAccountTotalCollectibleValueUseCase.kt
  app/src/main/kotlin/com/algorand/android/usecase/LedgerInformationUseCase.kt
  app/src/test/kotlin/com/algorand/android/modules/accountcore/domain/usecase/GetAccountTotalValueFlowUseCaseTest.kt
  common-sdk/src/main/kotlin/com/algorand/wallet/account/info/data/database/dao/AccountInformationDao.kt
  common-sdk/src/main/kotlin/com/algorand/wallet/account/info/data/repository/AccountInformationRepositoryImpl.kt
  common-sdk/src/main/kotlin/com/algorand/wallet/account/info/di/AccountInformationModule.kt
  common-sdk/src/main/kotlin/com/algorand/wallet/account/info/domain/repository/AccountInformationRepository.kt
  common-sdk/src/main/kotlin/com/algorand/wallet/account/info/domain/usecase/AccountInformationUseCases.kt
  common-sdk/src/test/kotlin/com/algorand/wallet/account/info/data/repository/AccountInformationRepositoryImplTest.kt
Labels: epic

#189 PERA-1284 :: Compose Ui for address list
  app/src/main/kotlin/com/algorand/android/modules/onboarding/recoverypassphrase/importaddresses/RecoverRegisteredAccountsContract.kt
  app/src/main/kotlin/com/algorand/android/modules/onboarding/recoverypassphrase/importaddresses/RecoverRegisteredAccountsFragment.kt
  app/src/main/kotlin/com/algorand/android/modules/onboarding/recoverypassphrase/importaddresses/RecoverRegisteredAccountsViewModel.kt
  app/src/main/kotlin/com/algorand/android/ui/compose/theme/PeraColor.kt
  app/src/main/kotlin/com/algorand/android/ui/compose/widget/PeraButton.kt
  app/src/main/kotlin/com/algorand/android/ui/compose/widget/PeraCard.kt
  app/src/main/kotlin/com/algorand/android/ui/compose/widget/PeraCheckbox.kt
  app/src/main/kotlin/com/algorand/android/ui/compose/widget/PeraText.kt
  app/src/main/res/values/strings.xml
  gradle/libs.versions.toml
Labels: external contribution

#190 PERA-1739 :: Quick actions buttons redesign phase 1
  app/src/main/kotlin/com/algorand/android/modules/accountdetail/assets/ui/AccountAssetsFragment.kt
  app/src/main/kotlin/com/algorand/android/modules/accountdetail/assets/ui/adapter/AccountAssetsAdapter.kt
  app/src/main/kotlin/com/algorand/android/modules/accountdetail/assets/ui/adapter/AccountDetailQuickActionsViewHolder.kt
  app/src/main/kotlin/com/algorand/android/modules/accountdetail/assets/ui/domain/AccountAssetsPreviewUseCase.kt
  app/src/main/kotlin/com/algorand/android/modules/accountdetail/assets/ui/model/QuickActionItem.kt
  app/src/main/kotlin/com/algorand/android/modules/accountdetail/ui/AccountDetailFragment.kt
  app/src/main/kotlin/com/algorand/android/modules/accounts/ui/AccountsFragment.kt
  app/src/main/kotlin/com/algorand/android/modules/accounts/ui/AccountsViewModel.kt
  app/src/main/kotlin/com/algorand/android/modules/accounts/ui/viewholder/AccountsQuickActionsViewHolder.kt
  app/src/main/kotlin/com/algorand/android/modules/tracking/core/Constants.kt
  app/src/main/res/layout/fragment_accounts.xml
  app/src/main/res/layout/item_accounts_quick_actions.xml
  app/src/main/res/values/dimens.xml
Labels: enhancement

#207 PERA-1786 :: Add in proguard rules for JNA library in project
  app/proguard-rules.pro
  common-sdk/build.gradle.kts
  common-sdk/src/main/kotlin/com/algorand/wallet/account/local/data/repository/HdSeedRepositoryImpl.kt
Labels: epic

#206 PERA-1799 :: Fix create account coroutine cancellation issue
  app/src/main/kotlin/com/algorand/android/mapper/NameRegistrationPreviewMapper.kt
  app/src/main/kotlin/com/algorand/android/ui/register/nameregistration/NameRegistrationViewModel.kt
Labels: epic

#204 PERA-1777 :: Remove GetLocalAccountUseCase and refactor the usages
  app/src/main/kotlin/com/algorand/android/MainActivity.kt
  app/src/main/kotlin/com/algorand/android/MainViewModel.kt
  app/src/main/kotlin/com/algorand/android/modules/accounts/ui/AccountsFragment.kt
  app/src/main/kotlin/com/algorand/android/modules/accounts/ui/AccountsViewModel.kt
  app/src/main/kotlin/com/algorand/android/modules/autolockmanager/domain/usecase/ShouldAppLockedUseCase.kt
  app/src/main/kotlin/com/algorand/android/modules/autolockmanager/ui/AutoLockManager.kt
  app/src/main/kotlin/com/algorand/android/modules/autolockmanager/ui/usecase/AutoLockManagerUseCase.kt
  app/src/main/kotlin/com/algorand/android/modules/onboarding/recoverypassphrase/qrscanner/ui/RecoverWithPassphraseQrScannerFragment.kt
  app/src/main/kotlin/com/algorand/android/modules/onboarding/recoverypassphrase/qrscanner/ui/RecoverWithPassphraseQrScannerViewModel.kt
  app/src/main/kotlin/com/algorand/android/modules/onboarding/recoverypassphrase/rekeyedaccountselection/information/ui/usecase/RekeyedAccountInformationPreviewUseCase.kt
  app/src/main/kotlin/com/algorand/android/modules/qrscanning/BaseQrScannerFragment.kt
  app/src/main/kotlin/com/algorand/android/ui/accounts/AccountsAddressScanActionBottomSheet.kt
  app/src/main/kotlin/com/algorand/android/ui/accounts/AccountsAddressScanActionViewModel.kt
  app/src/main/kotlin/com/algorand/android/ui/accounts/AccountsQrScannerFragment.kt
  app/src/main/kotlin/com/algorand/android/ui/accounts/AccountsQrScannerViewModel.kt
  app/src/main/kotlin/com/algorand/android/ui/register/nameregistration/BaseNameRegistrationFragment.kt
  app/src/main/kotlin/com/algorand/android/ui/register/nameregistration/NameRegistrationViewModel.kt
  app/src/main/kotlin/com/algorand/android/usecase/GetLocalAccountsUseCase.kt
  app/src/main/kotlin/com/algorand/android/usecase/IsAccountLimitExceedUseCase.kt
  app/src/main/kotlin/com/algorand/android/utils/inappreview/InAppReviewManager.kt
  app/src/main/res/navigation/main_navigation.xml
  common-sdk/src/main/kotlin/com/algorand/wallet/account/local/di/LocalAccountsModule.kt
  common-sdk/src/main/kotlin/com/algorand/wallet/account/local/domain/usecase/IsThereAnyLocalAccountUseCase.kt
Labels: epic

#216 PERA-1809 :: Fix QR scan account type bug
  app/src/main/kotlin/com/algorand/android/modules/qrscanning/BaseQrScannerFragment.kt
  app/src/main/res/navigation/recover_with_passphrase_navigation.xml
Labels: bug, epic

#215 PERA-1793 :: Hide backup banner if total account value is 0
  app/src/main/kotlin/com/algorand/android/modules/accounts/ui/AccountPreviewProcessor.kt
Labels: bug, epic

#218 PERA-1863 :: Fix key returning 0s in account-refactor branch
  app/src/main/kotlin/com/algorand/android/usecase/AccountAdditionUseCase.kt
  common-sdk/src/main/kotlin/com/algorand/wallet/account/core/domain/usecase/AddHdSeedUseCase.kt
  common-sdk/src/main/kotlin/com/algorand/wallet/algosdk/transaction/sdk/AlgoAccountSdkImpl.kt
  common-sdk/src/main/kotlin/com/algorand/wallet/algosdk/transaction/sdk/PeraBip39SdkImpl.kt
Labels: bug, epic

#221 PERA-1857 :: Remove ASB account selection screen
  app/src/main/kotlin/com/algorand/android/modules/asb/backedupaccountssource/data/di/BackedUpAccountsModule.kt
  app/src/main/kotlin/com/algorand/android/modules/asb/backedupaccountssource/data/local/BackedUpAccountsLocalSource.kt
  app/src/main/kotlin/com/algorand/android/modules/asb/backedupaccountssource/data/repository/BackedUpAccountsRepositoryImpl.kt
  app/src/main/kotlin/com/algorand/android/modules/asb/backedupaccountssource/domain/repository/BackedUpAccountsRepository.kt
  app/src/main/kotlin/com/algorand/android/modules/asb/backedupaccountssource/domain/usecase/AddBackedUpAccountListenerUseCase.kt
  app/src/main/kotlin/com/algorand/android/modules/asb/backedupaccountssource/domain/usecase/AddBackedUpAccountsUseCase.kt
  app/src/main/kotlin/com/algorand/android/modules/asb/backedupaccountssource/domain/usecase/ClearBackedUpAccountsUseCase.kt
  app/src/main/kotlin/com/algorand/android/modules/asb/backedupaccountssource/domain/usecase/GetBackedUpAccountsUseCase.kt
  app/src/main/kotlin/com/algorand/android/modules/asb/backedupaccountssource/domain/usecase/RemoveBackedUpAccountListenerUseCase.kt
  app/src/main/kotlin/com/algorand/android/modules/asb/backedupaccountssource/domain/usecase/RemoveBackedUpAccountUseCase.kt
  app/src/main/kotlin/com/algorand/android/modules/asb/createbackup/accountselection/ui/AsbCreationAccountSelectionFragment.kt
  app/src/main/kotlin/com/algorand/android/modules/asb/createbackup/accountselection/ui/AsbCreationAccountSelectionViewModel.kt
  app/src/main/kotlin/com/algorand/android/modules/asb/createbackup/accountselection/ui/mapper/AsbCreationAccountSelectionPreviewMapper.kt
  app/src/main/kotlin/com/algorand/android/modules/asb/createbackup/accountselection/ui/model/AsbCreationAccountSelectionPreview.kt
  app/src/main/kotlin/com/algorand/android/modules/asb/createbackup/accountselection/ui/usecase/AsbCreationAccountSelectionPreviewUseCase.kt
  app/src/main/kotlin/com/algorand/android/modules/asb/createbackup/filefailure/ui/AsbFileFailureFragment.kt
  app/src/main/kotlin/com/algorand/android/modules/asb/createbackup/intro/ui/AsbIntroFragment.kt
  app/src/main/kotlin/com/algorand/android/modules/asb/createbackup/intro/ui/AsbIntroViewModel.kt
  app/src/main/kotlin/com/algorand/android/modules/asb/createbackup/intro/ui/model/AsbIntroPreview.kt
  app/src/main/kotlin/com/algorand/android/modules/asb/createbackup/intro/ui/usecase/AsbPreviewUseCase.kt
  app/src/main/kotlin/com/algorand/android/modules/asb/createbackup/storekey/ui/AsbStoreKeyFragment.kt
  app/src/main/kotlin/com/algorand/android/modules/asb/createbackup/storekey/ui/AsbStoreKeyViewModel.kt
  app/src/main/kotlin/com/algorand/android/modules/asb/createbackup/storekey/ui/usecase/AsbStoreKeyPreviewUseCase.kt
  app/src/main/kotlin/com/algorand/android/modules/asb/util/AlgorandSecureBackupUtils.kt
  app/src/main/kotlin/com/algorand/android/modules/backupprotocol/domain/usecase/CreateBackupProtocolPayloadUseCase.kt
  app/src/main/kotlin/com/algorand/android/modules/settings/ui/usecase/SettingsPreviewUseCase.kt
  app/src/main/res/navigation/asb_creation_navigation.xml
  app/src/main/res/values/strings.xml
  common-sdk/src/main/kotlin/com/algorand/wallet/account/custom/data/database/dao/CustomAccountInfoDao.kt
  common-sdk/src/main/kotlin/com/algorand/wallet/account/custom/data/repository/CustomAccountInfoRepositoryImpl.kt
  common-sdk/src/main/kotlin/com/algorand/wallet/account/custom/di/CustomInfoModule.kt
  common-sdk/src/main/kotlin/com/algorand/wallet/account/custom/domain/repository/CustomAccountInfoRepository.kt
  common-sdk/src/main/kotlin/com/algorand/wallet/account/custom/domain/usecase/CustomInfoUseCases.kt
  common-sdk/src/main/kotlin/com/algorand/wallet/asb/di/AsbBackupModule.kt
  common-sdk/src/main/kotlin/com/algorand/wallet/asb/domain/usecase/BackupProtocolUseCases.kt
  common-sdk/src/main/kotlin/com/algorand/wallet/asb/domain/usecase/GetAsbEligibleAccountsUseCase.kt
  common-sdk/src/test/kotlin/com/algorand/wallet/account/custom/data/mapper/entity/CustomAccountInfoEntityMapperImpl.kt
  common-sdk/src/test/kotlin/com/algorand/wallet/account/custom/data/mapper/entity/CustomHdSeedInfoEntityMapperImplTest.kt
  common-sdk/src/test/kotlin/com/algorand/wallet/account/custom/data/mapper/model/CustomAccountInfoMapperImplTest.kt
  common-sdk/src/test/kotlin/com/algorand/wallet/account/custom/data/mapper/model/CustomHdSeedInfoMapperImplTest.kt
  common-sdk/src/test/kotlin/com/algorand/wallet/account/custom/data/repository/CustomAccountInfoRepositoryImplTest.kt
  common-sdk/src/test/kotlin/com/algorand/wallet/account/custom/data/repository/CustomHdSeedInfoRepositoryImplTest.kt
  common-sdk/src/test/kotlin/com/algorand/wallet/asb/domain/usecase/GetAsbEligibleAccountsUseCaseTest.kt
Labels: epic

#219 PERA-1867 :: lock in account-refactor v1 room schema
  common-sdk/schemas/com.algorand.wallet.account.local.data.database.AddressDatabase/1.json
  common-sdk/schemas/com.algorand.wallet.foundation.database.PeraDatabase/1.json
Labels: epic

#222 PERA-1877 :: Refresh settings screen when view is created
  app/src/main/kotlin/com/algorand/android/ui/settings/SettingsFragment.kt
  app/src/main/kotlin/com/algorand/android/ui/settings/SettingsViewModel.kt
Labels: bug, epic

#210 PERA-1812 :: Add migrateTo6X check in app start
  app/src/main/kotlin/com/algorand/android/core/PeraApp.kt
  app/src/main/kotlin/com/algorand/android/migration/Account6xMigrationManager.kt
  app/src/main/kotlin/com/algorand/android/migration/MigrationManager.kt
  app/src/main/kotlin/com/algorand/android/modules/algosdk/domain/usecase/BuildKeyRegOfflineTransactionImpl.kt
  app/src/main/kotlin/com/algorand/android/modules/settings/data/repository/MigrationTo6xRepositoryImpl.kt
  app/src/main/kotlin/com/algorand/android/modules/settings/di/SettingsModule.kt
  app/src/main/kotlin/com/algorand/android/modules/settings/domain/repository/MigrationTo6xRepository.kt
  app/src/main/kotlin/com/algorand/android/modules/settings/domain/usecase/MigrateTo6xUseCase.kt
  app/src/main/kotlin/com/algorand/android/modules/settings/domain/usecase/SettingsUseCases.kt
  app/src/main/kotlin/com/algorand/android/modules/settings/domain/utils/SettingsConstants.kt
  app/src/main/kotlin/com/algorand/android/ui/settings/SettingsViewModel.kt
  app/src/main/kotlin/com/algorand/android/ui/settings/developersettings/DeveloperSettingsViewModel.kt
  app/src/main/kotlin/com/algorand/android/ui/settings/mapper/SettingsPreviewMapper.kt
  app/src/main/kotlin/com/algorand/android/ui/settings/migrationviewer/MigrationViewerViewModel.kt
  app/src/main/kotlin/com/algorand/android/ui/settings/model/SettingsPreview.kt
  app/src/main/kotlin/com/algorand/android/ui/settings/usecase/DeveloperSettingsPreviewUseCase.kt
  app/src/main/kotlin/com/algorand/android/ui/settings/usecase/SettingsPreviewUseCase.kt
  app/src/test/kotlin/com/algorand/android/MigrateTo6xUseCaseTest.kt
  app/src/test/kotlin/com/algorand/android/modules/settings/data/repository/MigrationTo6xRepositoryImplTest.kt
  common-sdk/src/main/kotlin/com/algorand/wallet/algosdk/transaction/sdk/PeraBip39SdkImpl.kt
  common-sdk/src/main/kotlin/com/algorand/wallet/foundation/CommonModule.kt
  common-sdk/src/main/kotlin/com/algorand/wallet/foundation/manager/LifecycleAwareManager.kt
  common-sdk/src/main/kotlin/com/algorand/wallet/foundation/manager/LifecycleAwareManagerImpl.kt
Labels: epic

#229 PERA-1803 :: Fix account icon drawable issue
  app/src/main/kotlin/com/algorand/android/modules/accountcore/ui/usecase/GetAccountIconDrawablePreviewUseCase.kt
Labels: epic

#230 PERA-1815 :: Remove deprecated AssetDrawableProviderDecider functions
  app/src/main/kotlin/com/algorand/android/customviews/accountandassetitem/mapper/AssetItemConfigurationMapper.kt
  app/src/main/kotlin/com/algorand/android/customviews/accountandassetitem/mapper/CollectibleItemConfigurationMapper.kt
  app/src/main/kotlin/com/algorand/android/decider/AssetDrawableProviderDecider.kt
  app/src/main/kotlin/com/algorand/android/mapper/AssetSelectionMapper.kt
  app/src/main/kotlin/com/algorand/android/mapper/AssetTransferAmountAssetPreviewMapper.kt
  app/src/main/kotlin/com/algorand/android/mapper/RemoveAssetItemMapper.kt
  app/src/main/kotlin/com/algorand/android/modules/accountdetail/assets/ui/domain/AccountAssetsPreviewUseCase.kt
  app/src/main/kotlin/com/algorand/android/modules/accountdetail/assets/ui/mapper/AccountDetailAssetItemMapper.kt
  app/src/main/kotlin/com/algorand/android/modules/assetinbox/assetinboxoneaccount/ui/mapper/AssetInboxOneAccountPreviewMapper.kt
  app/src/main/kotlin/com/algorand/android/modules/assetinbox/assetinboxoneaccount/ui/mapper/AssetInboxOneAccountPreviewMapperImpl.kt
  app/src/main/kotlin/com/algorand/android/modules/assetinbox/assetinboxoneaccount/ui/usecase/AssetInboxOneAccountPreviewUseCase.kt
  app/src/main/kotlin/com/algorand/android/modules/assetinbox/detail/receivedetail/ui/mapper/Arc59ReceiveDetailPreviewMapperImpl.kt
  app/src/main/kotlin/com/algorand/android/modules/assets/profile/detail/ui/mapper/AssetDetailPreviewMapper.kt
  app/src/main/kotlin/com/algorand/android/modules/swap/assetselection/base/ui/mapper/SwapAssetSelectionItemMapper.kt
  app/src/main/kotlin/com/algorand/android/modules/swap/assetselection/fromasset/ui/usecase/SwapFromAssetSelectionPreviewUseCase.kt
  app/src/main/kotlin/com/algorand/android/modules/swap/assetswap/ui/mapper/SelectedAssetDetailMapper.kt
  app/src/main/kotlin/com/algorand/android/modules/swap/assetswap/ui/usecase/AssetSwapInitialPreviewUseCase.kt
  app/src/main/kotlin/com/algorand/android/modules/swap/assetswap/ui/usecase/AssetSwapPreviewAssetDetailUseCase.kt
  app/src/main/kotlin/com/algorand/android/modules/swap/confirmswap/ui/mapper/ConfirmSwapAssetDetailMapper.kt
  app/src/main/kotlin/com/algorand/android/modules/swap/confirmswap/ui/usecase/ConfirmSwapPreviewUseCase.kt
  app/src/main/kotlin/com/algorand/android/modules/transaction/detail/domain/usecase/ApplicationCallAssetsPreviewUseCase.kt
  app/src/main/kotlin/com/algorand/android/usecase/AssetSelectionUseCase.kt
  common-sdk/src/main/kotlin/com/algorand/wallet/asset/data/database/dao/CollectibleDao.kt
  common-sdk/src/main/kotlin/com/algorand/wallet/asset/data/repository/AssetDetailCacheHelper.kt
  common-sdk/src/main/kotlin/com/algorand/wallet/asset/data/repository/AssetDetailCacheHelperImpl.kt
  common-sdk/src/main/kotlin/com/algorand/wallet/asset/data/repository/AssetRepositoryImpl.kt
  common-sdk/src/main/kotlin/com/algorand/wallet/asset/di/AssetDetailUseCaseModule.kt
  common-sdk/src/main/kotlin/com/algorand/wallet/asset/domain/repository/AssetRepository.kt
  common-sdk/src/main/kotlin/com/algorand/wallet/asset/domain/usecase/AssetUseCases.kt
Labels: bug, epic

#231 PERA-1889 :: Update RecoverAccountResultInfoFragment ui
  app/src/main/kotlin/com/algorand/android/modules/onboarding/recoverypassphrase/result/ui/RecoverAccountResultInfoFragment.kt
Labels: bug, epic

#226 PERA-1793 :: Add in 0 balance check on account detail screen
  app/src/main/kotlin/com/algorand/android/modules/accountdetail/assets/ui/domain/AccountAssetsPreviewUseCase.kt
Labels: bug, epic

#225 PERA-1884 :: Fix backup flow crash on Account Detail
  app/src/main/kotlin/com/algorand/android/modules/accountdetail/ui/AccountDetailFragment.kt
  app/src/main/kotlin/com/algorand/android/modules/accountdetail/ui/AccountDetailViewModel.kt
  app/src/main/kotlin/com/algorand/android/modules/accounts/ui/AccountsFragment.kt
  app/src/main/kotlin/com/algorand/android/ui/common/warningconfirmation/BackupInfoFragment.kt
  app/src/main/kotlin/com/algorand/android/ui/common/warningconfirmation/WriteDownInfoFragment.kt
  app/src/main/kotlin/com/algorand/android/ui/register/BackupPassphraseFragment.kt
  app/src/main/kotlin/com/algorand/android/ui/register/BackupPassphraseViewModel.kt
  app/src/main/kotlin/com/algorand/android/ui/register/PassphraseValidationFragment.kt
  app/src/main/kotlin/com/algorand/android/ui/register/PassphraseValidationViewModel.kt
  app/src/main/kotlin/com/algorand/android/ui/register/registerintro/RegisterIntroFragment.kt
  app/src/main/res/navigation/backup_passphrase_info_navigation.xml
  app/src/main/res/navigation/backup_passphrase_navigation.xml
  app/src/main/res/navigation/home_navigation.xml
  app/src/main/res/navigation/login_navigation.xml
  common-sdk/src/main/kotlin/com/algorand/wallet/algosdk/transaction/sdk/AlgoAccountSdkImpl.kt
Labels: bug, epic

#227 PERA-1888 :: update is_backed_up to mean verifying passphrase test and not ASB
  app/src/main/kotlin/com/algorand/android/core/AccountManager.kt
  app/src/main/kotlin/com/algorand/android/modules/accounts/ui/AccountPreviewProcessor.kt
  app/src/main/kotlin/com/algorand/android/modules/asb/createbackup/storekey/ui/usecase/AsbStoreKeyPreviewUseCase.kt
  app/src/main/kotlin/com/algorand/android/ui/register/PassphraseValidationFragment.kt
  app/src/main/kotlin/com/algorand/android/ui/register/PassphraseValidationViewModel.kt
  common-sdk/src/main/kotlin/com/algorand/wallet/account/custom/di/CustomInfoModule.kt
  common-sdk/src/main/kotlin/com/algorand/wallet/account/custom/domain/usecase/CustomInfoUseCases.kt
Labels: bug, epic

#228 PERA-1876 :: Implement delete all data flows
  app/src/main/kotlin/com/algorand/android/core/PeraApp.kt
  app/src/main/kotlin/com/algorand/android/migration/MigrationManager.kt
  app/src/main/kotlin/com/algorand/android/modules/inapppin/pin/ui/usecase/InAppPinPreviewUseCase.kt
  app/src/main/kotlin/com/algorand/android/modules/lock/ui/LockFragment.kt
  app/src/main/kotlin/com/algorand/android/modules/lock/ui/LockViewModel.kt
  app/src/main/kotlin/com/algorand/android/ui/settings/SettingsFragment.kt
  app/src/main/kotlin/com/algorand/android/ui/settings/SettingsViewModel.kt
  app/src/main/kotlin/com/algorand/android/usecase/DeleteAllDataUseCase.kt
  common-sdk/src/main/kotlin/com/algorand/wallet/account/custom/data/repository/CustomAccountInfoRepositoryImpl.kt
  common-sdk/src/main/kotlin/com/algorand/wallet/account/custom/data/repository/CustomHdSeedInfoRepositoryImpl.kt
  common-sdk/src/main/kotlin/com/algorand/wallet/account/custom/di/CustomInfoModule.kt
  common-sdk/src/main/kotlin/com/algorand/wallet/account/custom/domain/repository/CustomAccountInfoRepository.kt
  common-sdk/src/main/kotlin/com/algorand/wallet/account/custom/domain/repository/CustomHdSeedInfoRepository.kt
  common-sdk/src/main/kotlin/com/algorand/wallet/account/custom/domain/usecase/ClearAllCustomInformationUseCase.kt
  common-sdk/src/main/kotlin/com/algorand/wallet/account/custom/domain/usecase/CustomInfoUseCases.kt
  common-sdk/src/main/kotlin/com/algorand/wallet/account/local/di/LocalAccountsModule.kt
  common-sdk/src/main/kotlin/com/algorand/wallet/account/local/domain/usecase/DeleteAllLocalAccountsUseCase.kt
  common-sdk/src/main/kotlin/com/algorand/wallet/account/local/domain/usecase/LocalAccountUseCases.kt
  common-sdk/src/test/kotlin/com/algorand/wallet/account/custom/domain/usecase/ClearAllCustomInformationUseCaseTest.kt
  common-sdk/src/test/kotlin/com/algorand/wallet/account/local/domain/usecase/DeleteAllLocalAccountsUseCaseTest.kt
Labels: bug, epic
